"""
Django settings for land_escrow project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY: SECRET_KEY must be set via environment variable in production.
# In development, a fixed default is acceptable but must NEVER be used in production.
SECRET_KEY = config('SECRET_KEY')  # No default — must be explicitly set

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)
TESTING = "test" in sys.argv

ALLOWED_HOSTS = [
    h.strip()
    for h in config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8000').split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.microsoft',
    'widget_tweaks',

    # Third Party
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'django_celery_beat',
    'drf_spectacular',
    'corsheaders',
    'tenants',
    'core',
    'server.apps.ServerConfig',
    'cloudinary',
    'cloudinary_storage',

    # Admin Control Plane
    'admin_control_plane',

    # External Services Layer
    'external_services',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.LegacyBrowseRedirectMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Request ID middleware — must be before any request processing for log correlation
    'core.log_filters.RequestIDMiddleware',
    'core.middleware.EmailVerificationGateMiddleware',
    'tenants.middleware.TenantMiddleware',

    # Graceful Degradation & Resilience Middleware
    'core.error_middleware.DatabaseDegradationMiddleware',
    'core.error_middleware.ExternalServiceDegradationMiddleware',
    'core.error_middleware.GracefulDegradationMiddleware',

    'core.middleware.AgentKYCGateMiddleware',
    'core.middleware.RBACMiddleware',
    'core.middleware.RateLimitMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'core.middleware.SecurityAuditMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

    # Admin Control Plane middleware (network isolation, MFA, session security, audit)
    'admin_control_plane.middleware.AdminNetworkIsolationMiddleware',
    'admin_control_plane.middleware.AdminMFAEnforcementMiddleware',
    'admin_control_plane.middleware.AdminSessionSecurityMiddleware',
    'admin_control_plane.middleware.AdminAuditMiddleware',
]

ROOT_URLCONF = 'land_escrow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'land_escrow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# ── Password Hashing: Argon2id preferred ─────────────────────────────────────
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'core.validators.ComplexityPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Only include optional frontend build output when it exists.
STATICFILES_DIRS = [
    static_dir
    for static_dir in (
        BASE_DIR / 'client' / 'dist',
        BASE_DIR / 'static',
    )
    if static_dir.exists()
]

# Cloudinary Setup for entirely Free Media (PDFs, Images) hosting
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME', default=''),
    'API_KEY': config('CLOUDINARY_API_KEY', default=''),
    'API_SECRET': config('CLOUDINARY_API_SECRET', default='')
}

if config('CLOUDINARY_CLOUD_NAME', default=''):
    # Use Raw Storage to support PDFs and Docx uploaded for Land Titles
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'
else:
    # Fallback to local
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Custom user model
AUTH_USER_MODEL = 'core.User'

# ── REST Framework ───────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# ── Simple JWT ────────────────────────────────────────────────────────────────
if TESTING:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('JWT_SIGNING_KEY', default=SECRET_KEY),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# ── Celery ────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_ALWAYS_EAGER = config('CELERY_TASK_ALWAYS_EAGER', default=True, cast=bool)
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers.DatabaseScheduler'

# ── Cache (Redis with fallback to locmem) ─────────────────────────────────────
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/0')

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'digiland-dev-cache',
    }
}

# If Redis is available, use it instead of locmem
if config('USE_REDIS_CACHE', default=False, cast=bool):
    CACHES['default'] = {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL,
        'KEY_PREFIX': 'digiland',
        'TIMEOUT': 300,
    }

# ── Stripe ────────────────────────────────────────────────────────────────────
STRIPE_PUBLIC_KEY = config('STRIPE_PUBLIC_KEY', default='')
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')

# ── DRF Spectacular (API Documentation) ───────────────────────────────────────
SPECTACULAR_SETTINGS = {
    'TITLE': 'Digiland API',
    'DESCRIPTION': 'Land escrow platform API documentation',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
}

# ── Logging ───────────────────────────────────────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(name)s %(process)d %(thread)d %(message)s',
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'external_services': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'admin_control_plane': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Resilience & Graceful Degradation logging
        'core.error_middleware': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'core.error_responses': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'core.financial_error_handler': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.auth_error_handler': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.admin_error_handler': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.db_degradation': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.third_party_degradation': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'core.observability': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core.background_job_monitor': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# CORS — restricted even in development
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in config('CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://localhost:8000').split(',')
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-request-id',
    'x-mpesa-secret',
]

# M-PESA callback secret for verifying incoming Safaricom callbacks
MPESA_CALLBACK_SECRET = config('MPESA_CALLBACK_SECRET', default='')

# ── Email Configuration ────────────────────────────────────────────────────────
# Local development: uses Django's console email backend unless SMTP
# credentials are configured, in which case we prefer real delivery during
# normal runtime. Test runs remain isolated.
EMAIL_BACKEND = config("EMAIL_BACKEND", default="").strip()
EMAIL_HOST = config("EMAIL_HOST", cast=str, default="smtp.gmail.com").strip()
EMAIL_PORT = config("EMAIL_PORT", cast=int, default=587)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", cast=str, default="").strip()
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", cast=str, default="").strip()
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=True)  # Use EMAIL_PORT 587 for TLS
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)  # Use EMAIL_PORT 465 for SSL
ADMIN_USER_NAME = config("ADMIN_USER_NAME", default="Digiland Admin")
ADMIN_USER_EMAIL = config("ADMIN_USER_EMAIL", default="")

# The "From" address is its own setting, independent of the SMTP login.
# It must NEVER resolve to a blank string or Django will crash with
# ValueError: Invalid address '' when trying to send a verification email.
DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="",
) or config(
    "EMAIL_HOST_USER",
    default="",
) or "noreply@digiland.local"

if DEBUG and not TESTING and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    if not EMAIL_BACKEND or EMAIL_BACKEND == "django.core.mail.backends.console.EmailBackend":
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    if DEFAULT_FROM_EMAIL.lower() in {
        "noreply@digiland.local",
        "noreply@digiland.co.ke",
        "no-reply@digiland.local",
        "no-reply@digiland.co.ke",
    }:
        DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

if not EMAIL_BACKEND:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

SERVER_EMAIL = DEFAULT_FROM_EMAIL

MANAGERS = []
ADMINS = []
if ADMIN_USER_NAME and ADMIN_USER_EMAIL:
    ADMINS += [(f'{ADMIN_USER_NAME}', f'{ADMIN_USER_EMAIL}')]
    MANAGERS = ADMINS

# Paystack Configuration
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY', default='')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', default='')

# GavaConnect KRA API Configuration (OAuth2)
# App: Digiland — PIN Checker BY ID
GAVACONNECT_CONSUMER_KEY = config('GAVACONNECT_CONSUMER_KEY', default='')
GAVACONNECT_CONSUMER_SECRET = config('GAVACONNECT_CONSUMER_SECRET', default='')
# App: DigilandFull — PIN Checker by PIN
GAVACONNECT_PIN_CONSUMER_KEY = config('GAVACONNECT_PIN_CONSUMER_KEY', default='')
GAVACONNECT_PIN_CONSUMER_SECRET = config('GAVACONNECT_PIN_CONSUMER_SECRET', default='')
# App: Digiland Escrow — Tax Compliance Certificate Checker
GAVACONNECT_TCC_CONSUMER_KEY = config('GAVACONNECT_TCC_CONSUMER_KEY', default='')
GAVACONNECT_TCC_CONSUMER_SECRET = config('GAVACONNECT_TCC_CONSUMER_SECRET', default='')
# Shared
GAVACONNECT_BASE_URL = config('GAVACONNECT_BASE_URL', default='https://sbx.kra.go.ke')
GAVACONNECT_ENVIRONMENT = config('GAVACONNECT_ENVIRONMENT', default='sandbox')

# ── KRA PIN Database Validation Toggle ──────────────────────────────────────
# When False (default), KRA PIN validation uses FORMAT ONLY — the regex
# check [A-Z]{1}\d{9}[A-Z]{1} is sufficient for signup/KYC.  The KRA
# iTax and GavaConnect APIs are usually down, which blocks account creation.
#
# When True, the system calls the KRA database (iTax + GavaConnect) to
# verify the PIN actually exists.  Enable this in PRODUCTION as a failover
# once the KRA API uptime is confirmed.
KRA_DB_VALIDATION_ENABLED = config('KRA_DB_VALIDATION_ENABLED', default=False, cast=bool)

# Safaricom Daraja API Configuration
DARAJA_CONSUMER_KEY = config('DARAJA_CONSUMER_KEY', default='')
DARAJA_CONSUMER_SECRET = config('DARAJA_CONSUMER_SECRET', default='')
DARAJA_SHORTCODE = config('DARAJA_SHORTCODE', default='')
DARAJA_PASSKEY = config('DARAJA_PASSKEY', default='')
DARAJA_INITIATOR_NAME = config('DARAJA_INITIATOR_NAME', default='')
DARAJA_INITIATOR_PASSWORD = config('DARAJA_INITIATOR_PASSWORD', default='')
DARAJA_ENVIRONMENT = config('DARAJA_ENVIRONMENT', default='sandbox')

# KCB Bank API Configuration
KCB_API_BASE_URL = config('KCB_API_BASE_URL', default='https://uat.bfrg.co.ke:8443/api')
KCB_CLIENT_ID = config('KCB_CLIENT_ID', default='')
KCB_CLIENT_SECRET = config('KCB_CLIENT_SECRET', default='')
KCB_COMPANY_CODE = config('KCB_COMPANY_CODE', default='')
KCB_PLATFORM_ACCOUNT = config('KCB_PLATFORM_ACCOUNT', default='DIGILAND-ESCROW-001')
KCB_SANDBOX = config('KCB_SANDBOX', default=True, cast=bool)

# Admin Finance Dashboard — REMOVED hardcoded PIN.
# Admin financial operations must go through proper Django admin with MFA.
# ADMIN_FINANCE_PIN is DEPRECATED and must not be used.

# API Configuration
API_TIMEOUT_SECONDS = config('API_TIMEOUT_SECONDS', default=30, cast=int)
API_RETRY_ATTEMPTS = config('API_RETRY_ATTEMPTS', default=3, cast=int)

# Logging Configuration
ENABLE_API_LOGGING = config('ENABLE_API_LOGGING', default=True, cast=bool)
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

# Allauth Configuration
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'core.auth_backends.EmailOrUsernameModelBackend',
    'core.auth_backends.MFAAuthenticationBackend',
    'core.auth_backends.DeviceTrustAuthenticationBackend',
    'core.auth_backends.OAuthAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
# allauth 65.x modern settings (replaces deprecated EMAIL_REQUIRED / USERNAME_REQUIRED / AUTHENTICATION_METHOD)
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_SIGNUP_FORM_CLASS = 'core.forms.CustomSignupForm'
ACCOUNT_ADAPTER = 'core.adapter.RoleBasedAccountAdapter'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# ── Session Security ────────────────────────────────────────────────────────────
SESSION_COOKIE_SECURE = not DEBUG  # True in production
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=3600, cast=int)  # 1 hour

# ── Security Headers ───────────────────────────────────────────────────────────
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Data Upload Limits ──────────────────────────────────────────────────────────
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

# ── Multi-Tenant Configuration ──────────────────────────────────────────────────
TENANT_HEADER = 'HTTP_X_TENANT_ID'  # Header name for tenant identification
TENANT_JWT_CLAIM = 'tenant_id'       # JWT claim key for tenant ID
TENANT_RESOLVE_ORDER = ['jwt', 'header', 'default_org']  # Resolution priority
TENANT_ALLOW_NULL = True             # Allow requests without tenant context (admin)
TENANT_CACHE_SECONDS = 300           # Cache org lookups for 5 minutes

# ── RBAC Rules ──────────────────────────────────────────────────────────────────
RBAC_RULES = {
    '/api/v1/admin/': ['Admin'],
    '/api/v1/audit-logs/': ['Admin'],
    '/api/v1/analytics/platform-revenue/': ['Admin'],
    '/api/v1/analytics/buyer-segments/': ['Admin'],
}

# ── Rate Limiting ──────────────────────────────────────────────────────────────
RATE_LIMIT_DEFAULT = '100/60'
RATE_LIMIT_PER_PATH = {
    '/api/v1/auth/login': '10/60',
    '/api/v1/auth/register': '5/60',
    '/api/v1/auth/mfa/': '10/60',
    '/api/v1/auth/password-reset/': '5/60',
    '/api/v1/auth/oauth/': '20/60',
    '/api/v1/mpesa/': '30/60',
    '/api/v1/payments/': '30/60',
    '/api/v1/verification/': '10/60',
}

# ── Brute-Force Protection ────────────────────────────────────────────────────
BRUTE_FORCE_MAX_ATTEMPTS = config('BRUTE_FORCE_MAX_ATTEMPTS', default=5, cast=int)
BRUTE_FORCE_WINDOW_MINUTES = config('BRUTE_FORCE_WINDOW_MINUTES', default=15, cast=int)

# ── MFA Configuration ─────────────────────────────────────────────────────────
MFA_TOTP_ISSUER = 'Digiland'
MFA_RECOVERY_CODE_COUNT = 8
MFA_TRUST_DURATION_DAYS = 30
MFA_STEP_UP_DURATION_MINUTES = 5

# ── OAuth/SSO Configuration ──────────────────────────────────────────────────
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# ── Admin Control Plane Settings ──────────────────────────────────────────────
ADMIN_PATH_PREFIXES = ['/admin/', '/api/v1/admin/']
ADMIN_ALLOWED_IP_RANGES = [
    ip.strip()
    for ip in config('ADMIN_ALLOWED_IP_RANGES', default='').split(',')
    if ip.strip()
]
# Default: empty list = allow all (dev mode).  Production MUST set this.
ADMIN_SESSION_IDLE_TIMEOUT_SECONDS = config(
    'ADMIN_SESSION_IDLE_TIMEOUT_SECONDS', default=1800, cast=int,
)  # 30 minutes
ADMIN_SESSION_ABSOLUTE_TIMEOUT_SECONDS = config(
    'ADMIN_SESSION_ABSOLUTE_TIMEOUT_SECONDS', default=14400, cast=int,
)  # 4 hours
ADMIN_SESSION_TERMINATE_ON_IP_CHANGE = config(
    'ADMIN_SESSION_TERMINATE_ON_IP_CHANGE', default=True, cast=bool,
)
ADMIN_SESSION_TERMINATE_ON_DEVICE_CHANGE = config(
    'ADMIN_SESSION_TERMINATE_ON_DEVICE_CHANGE', default=False, cast=bool,
)
ADMIN_TRUSTED_PROXY_COUNT = config(
    'ADMIN_TRUSTED_PROXY_COUNT', default=0, cast=int,
)

# ── External Services Layer Settings ───────────────────────────────────────────
ESL_IP_ALLOWLIST = [
    ip.strip()
    for ip in config('ESL_IP_ALLOWLIST', default='').split(',')
    if ip.strip()
]
ESL_ENFORCE_HTTPS = not DEBUG
ESL_EVENT_BACKEND = config('ESL_EVENT_BACKEND', default='redis')
ESL_WEBHOOK_SECRET_PAYSTACK = config('ESL_WEBHOOK_SECRET_PAYSTACK', default='')
ESL_WEBHOOK_SECRET_STRIPE = config('ESL_WEBHOOK_SECRET_STRIPE', default='')
ESL_PAYSTACK_SIGNING_SECRET = config('ESL_PAYSTACK_SIGNING_SECRET', default='')
ESL_STRIPE_SIGNING_SECRET = config('ESL_STRIPE_SIGNING_SECRET', default='')
ESL_DEFAULT_TIMEOUT_SECONDS = config('ESL_DEFAULT_TIMEOUT_SECONDS', default=30, cast=int)
ESL_MAX_RETRIES = config('ESL_MAX_RETRIES', default=3, cast=int)
ESL_CIRCUIT_BREAKER_FAILURE_THRESHOLD = config(
    'ESL_CIRCUIT_BREAKER_FAILURE_THRESHOLD', default=5, cast=int,
)
ESL_CIRCUIT_BREAKER_RECOVERY_TIMEOUT = config(
    'ESL_CIRCUIT_BREAKER_RECOVERY_TIMEOUT', default=60, cast=int,
)

# ── WebAuthn Configuration ────────────────────────────────────────────────────
WEBAUTHN_RP_ID = config('WEBAUTHN_RP_ID', default='localhost')
WEBAUTHN_RP_NAME = config('WEBAUTHN_RP_NAME', default='Digiland')
WEBAUTHN_RP_ORIGIN = config('WEBAUTHN_RP_ORIGIN', default='http://localhost:8000')
WEBAUTHN_MAX_CREDENTIALS_PER_USER = config('WEBAUTHN_MAX_CREDENTIALS_PER_USER', default=5, cast=int)
WEBAUTHN_CHALLENGE_TTL_SECONDS = config('WEBAUTHN_CHALLENGE_TTL_SECONDS', default=300, cast=int)

# ── Dual Approval (Four-Eyes Principle) ──────────────────────────────────────
DUAL_APPROVAL_ENABLED = config('DUAL_APPROVAL_ENABLED', default=True, cast=bool)
DUAL_APPROVAL_CRITICAL_THRESHOLD = config('DUAL_APPROVAL_CRITICAL_THRESHOLD', default=2000000, cast=int)
DUAL_APPROVAL_ACTION_EXPIRY_HOURS = config('DUAL_APPROVAL_ACTION_EXPIRY_HOURS', default=24, cast=int)
DUAL_APPROVAL_REQUIRE_HARDWARE_KEY_ABOVE = config('DUAL_APPROVAL_REQUIRE_HARDWARE_KEY_ABOVE', default=2000000, cast=int)

# ── Secrets Vault Configuration ──────────────────────────────────────────────
SECRETS_VAULT_MASTER_KEY = config('SECRETS_VAULT_MASTER_KEY', default='')
SECRETS_VAULT_DEFAULT_ROTATION_DAYS = config('SECRETS_VAULT_DEFAULT_ROTATION_DAYS', default=90, cast=int)
SECRETS_VAULT_ACCESS_RATE_LIMIT_PER_MINUTE = config('SECRETS_VAULT_ACCESS_RATE_LIMIT_PER_MINUTE', default=30, cast=int)
SECRETS_VAULT_ACCESS_RATE_LIMIT_PER_HOUR = config('SECRETS_VAULT_ACCESS_RATE_LIMIT_PER_HOUR', default=200, cast=int)

# ── SIEM Integration Configuration ────────────────────────────────────────────
SIEM_ENABLED = config('SIEM_ENABLED', default=False, cast=bool)
SIEM_ENDPOINT_URL = config('SIEM_ENDPOINT_URL', default='')
SIEM_API_KEY = config('SIEM_API_KEY', default='')
SIEM_OUTPUT_FORMAT = config('SIEM_OUTPUT_FORMAT', default='json')  # json, cef, syslog
SIEM_BATCH_SIZE = config('SIEM_BATCH_SIZE', default=100, cast=int)

# ── Emergency Controls Configuration ──────────────────────────────────────────
EMERGENCY_TEMP_ADMIN_MAX_LIFETIME_HOURS = config('EMERGENCY_TEMP_ADMIN_MAX_LIFETIME_HOURS', default=24, cast=int)
EMERGENCY_INCIDENT_RESPONDERS = [
    email.strip()
    for email in config('EMERGENCY_INCIDENT_RESPONDERS', default='').split(',')
    if email.strip()
]

# ── OAuth/SSO Configuration ──────────────────────────────────────────────────
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_OAUTH_CLIENT_ID', default=''),
            'secret': config('GOOGLE_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'github': {
        'APP': {
            'client_id': config('GITHUB_OAUTH_CLIENT_ID', default=''),
            'secret': config('GITHUB_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
        'SCOPE': ['user:email'],
    },
    'microsoft': {
        'APP': {
            'client_id': config('MICROSOFT_OAUTH_CLIENT_ID', default=''),
            'secret': config('MICROSOFT_OAUTH_CLIENT_SECRET', default=''),
            'key': '',
        },
    },
}

# ── Graceful Degradation & Resilience Settings ─────────────────────────────────
DJANGO_ENV = config('DJANGO_ENV', default='development')  # development | staging | production

# Error disclosure levels: 'full' (dev), 'limited' (staging), 'safe' (production)
ERROR_DISCLOSURE_LEVEL = config(
    'ERROR_DISCLOSURE_LEVEL',
    default='full' if DEBUG else 'safe',
)

# Database degradation settings
DB_DEGRADATION_READ_ONLY_TTL = config('DB_DEGRADATION_READ_ONLY_TTL', default=300, cast=int)  # 5 minutes
DB_DEGRADATION_SLOW_QUERY_THRESHOLD_MS = config(
    'DB_DEGRADATION_SLOW_QUERY_THRESHOLD_MS', default=5000, cast=int,
)  # 5 seconds
DB_DEGRADATION_SLOW_QUERY_COUNT_TRIGGER = config(
    'DB_DEGRADATION_SLOW_QUERY_COUNT_TRIGGER', default=3, cast=int,
)
DB_DEGRADATION_CACHE_RESPONSE_TTL = config(
    'DB_DEGRADATION_CACHE_RESPONSE_TTL', default=60, cast=int,
)  # 1 minute

# Background job monitoring settings
BG_JOB_STATUS_TTL = config('BG_JOB_STATUS_TTL', default=86400, cast=int)  # 24 hours
BG_JOB_MAX_RETRY_ATTEMPTS = config('BG_JOB_MAX_RETRY_ATTEMPTS', default=3, cast=int)

# Observability settings
OBSERVABILITY_ENABLED = config('OBSERVABILITY_ENABLED', default=True, cast=bool)
OBSERVABILITY_METRICS_TTL = config('OBSERVABILITY_METRICS_TTL', default=3600, cast=int)  # 1 hour
OBSERVABILITY_ERROR_RATE_WINDOW = config(
    'OBSERVABILITY_ERROR_RATE_WINDOW', default=300, cast=int,
)  # 5 minutes

# Sentry DSN for error tracking (optional)
SENTRY_DSN = config('SENTRY_DSN', default='')
SENTRY_TRACES_SAMPLE_RATE = config('SENTRY_TRACES_SAMPLE_RATE', default=0.1, cast=float)
SENTRY_ENVIRONMENT = DJANGO_ENV
