# Generated by Django 6.0.3 on 2026-06-03 12:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('session_token', models.CharField(db_index=True, help_text='Opaque token identifying this admin session.', max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Client IP address at session creation.')),
                ('user_agent', models.TextField(blank=True, default='', help_text='HTTP User-Agent header at session creation.')),
                ('device_fingerprint', models.CharField(blank=True, default='', help_text='Browser / device fingerprint hash for anomaly detection.', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False once the session is explicitly terminated or expired.')),
                ('mfa_verified_at', models.DateTimeField(blank=True, help_text='Timestamp when MFA was successfully verified for this session.', null=True)),
                ('hardware_key_verified', models.BooleanField(default=False, help_text='Whether a hardware security key (WebAuthn) was used.')),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Updated on every request – used for idle timeout.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Idle timeout deadline.  Refreshed on each request.')),
                ('absolute_expires_at', models.DateTimeField(help_text='Hard ceiling – session cannot be renewed past this time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('terminated_at', models.DateTimeField(blank=True, help_text='When the session was terminated, if applicable.', null=True)),
                ('termination_reason', models.CharField(blank=True, default='', help_text="Reason for termination: 'idle_timeout', 'absolute_expiry', 'manual', 'security_event', 'emergency_revocation', etc.", max_length=100)),
                ('user', models.ForeignKey(help_text='The administrator who owns this session.', on_delete=django.db.models.deletion.CASCADE, related_name='admin_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Session',
                'verbose_name_plural': 'Admin Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('action_type', models.CharField(choices=[('user_verify', 'User Verification'), ('kyc_approve', 'KYC Approval'), ('financial', 'Financial Operation'), ('withdrawal_approve', 'Withdrawal Approval'), ('permission_change', 'Permission Change'), ('role_change', 'Role Change'), ('admin_create', 'Admin Account Creation'), ('config_change', 'Configuration Change'), ('emergency', 'Emergency Action')], db_index=True, help_text='Category of the administrative action.', max_length=30)),
                ('resource_type', models.CharField(help_text="Type of resource affected, e.g. 'User', 'Transaction'.", max_length=100)),
                ('resource_id', models.CharField(help_text='Primary key of the affected resource (string for flexibility).', max_length=100)),
                ('action_details', models.JSONField(blank=True, default=dict, help_text='Arbitrary details about the action for audit purposes.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP at the time of the action.', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='HTTP User-Agent at the time of the action.')),
                ('device_fingerprint', models.CharField(blank=True, default='', help_text='Device fingerprint at the time of the action.', max_length=128)),
                ('step_up_auth', models.BooleanField(default=False, help_text='Whether step-up authentication was verified for this action.')),
                ('dual_approval', models.BooleanField(default=False, help_text='Whether dual approval was obtained for this action.')),
                ('risk_score', models.FloatField(default=0.0, help_text='Calculated risk score (0-100) for this action.')),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='Flagged for review by the risk-scoring engine.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred.')),
                ('hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of this record for tamper detection.', max_length=64)),
                ('previous_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the preceding record (chain integrity).', max_length=64)),
                ('actor', models.ForeignKey(help_text='Administrator who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(blank=True, help_text='Second approver for dual-approval actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Admin session under which the action was performed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='admin_control_plane.adminsession')),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DualApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('request_type', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('balance_adjustment', 'Balance Adjustment'), ('payout', 'Payout'), ('transfer', 'Transfer'), ('role_change', 'Role Change'), ('permission_change', 'Permission Change'), ('user_suspend', 'User Suspension'), ('config_change', 'Configuration Change')], db_index=True, help_text='Category of the requested action.', max_length=30)),
                ('resource_type', models.CharField(help_text='Type of resource the action targets.', max_length=100)),
                ('resource_id', models.CharField(help_text='Primary key of the target resource.', max_length=100)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Payload describing the requested action.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current lifecycle status of the request.', max_length=20)),
                ('risk_score', models.FloatField(default=0.0, help_text='Calculated risk score (0-100) at the time of request.')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary value involved, if applicable.', max_digits=18, null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved or rejected.', null=True)),
                ('requester_step_up_verified', models.BooleanField(default=False, help_text='Whether the requester completed step-up authentication.')),
                ('approver_step_up_verified', models.BooleanField(default=False, help_text='Whether the approver completed step-up authentication.')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Deadline by which the request must be approved.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the request reached a terminal state.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes from the requester or approver.')),
                ('approver', models.ForeignKey(blank=True, help_text='Administrator who approved or rejected the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dual_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='Administrator who requested the action.', on_delete=django.db.models.deletion.CASCADE, related_name='dual_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dual Approval Request',
                'verbose_name_plural': 'Dual Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('control_type', models.CharField(choices=[('withdrawal_freeze', 'Withdrawal Freeze'), ('session_revocation', 'Session Revocation'), ('account_lockdown', 'Account Lockdown'), ('incident_mode', 'Incident Mode'), ('admin_lockout', 'Admin Lockout')], db_index=True, help_text='Type of emergency control.', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='True while the control is in effect.')),
                ('activated_at', models.DateTimeField(auto_now_add=True, help_text='When the control was activated.')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When the control was deactivated.', null=True)),
                ('reason', models.TextField(help_text='Mandatory reason for activating the emergency control.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Optional configuration for the control, e.g. scope filters.')),
                ('activated_by', models.ForeignKey(help_text='Administrator who activated the control.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_emergency_controls', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, help_text='Administrator who deactivated the control.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_emergency_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Control',
                'verbose_name_plural': 'Emergency Controls',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminAccessPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this policy.', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('name', models.CharField(help_text="Human-readable policy name, e.g. 'Production VPN Only'.", max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of what this policy enforces.')),
                ('policy_type', models.CharField(choices=[('network', 'Network'), ('auth', 'Authentication'), ('action', 'Action'), ('financial', 'Financial')], db_index=True, help_text='Category of the policy – determines the rule schema.', max_length=20)),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Policy rule payload.  Schema varies by policy_type.')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive policies are skipped during evaluation.')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Evaluation order – lower number = higher priority.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Administrator who created this policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Access Policy',
                'verbose_name_plural': 'Admin Access Policies',
                'ordering': ['priority', 'name'],
                'indexes': [models.Index(fields=['tenant_id', 'policy_type', 'is_active'], name='idx_policy_tenant_type_active'), models.Index(fields=['tenant_id', 'priority'], name='idx_policy_tenant_priority')],
            },
        ),
        migrations.CreateModel(
            name='AdminIPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organisation tenant ID for row-level security isolation.', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Individual IP address allowed for admin access.')),
                ('ip_range', models.CharField(blank=True, default='', help_text="CIDR notation range, e.g. '10.0.0.0/8'.  Takes precedence over ip_address.", max_length=50)),
                ('label', models.CharField(blank=True, default='', help_text="Human-readable label, e.g. 'Office VPN', 'Data Center'.", max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive entries are skipped during IP validation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='If set, this entry applies only to the specified user. If null, it applies globally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowed_admin_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin IP Address',
                'verbose_name_plural': 'Admin IP Addresses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_adminip_user_active'), models.Index(fields=['tenant_id', 'is_active'], name='idx_adminip_tenant_active')],
            },
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['user', 'is_active'], name='idx_admsess_user_active'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['session_token'], name='idx_admsess_token'),
        ),
        migrations.AddIndex(
            model_name='adminsession',
            index=models.Index(fields=['expires_at'], name='idx_admsess_expires'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['actor', 'timestamp'], name='idx_actlog_actor_ts'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='idx_actlog_type_ts'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='idx_actlog_res_type_id'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['timestamp'], name='idx_actlog_timestamp'),
        ),
        migrations.AddIndex(
            model_name='adminactionlog',
            index=models.Index(fields=['tenant_id', 'timestamp'], name='idx_actlog_tenant_ts'),
        ),
        migrations.AddIndex(
            model_name='dualapprovalrequest',
            index=models.Index(fields=['status', 'created_at'], name='idx_dual_status_created'),
        ),
        migrations.AddIndex(
            model_name='dualapprovalrequest',
            index=models.Index(fields=['requester'], name='idx_dual_requester'),
        ),
        migrations.AddIndex(
            model_name='dualapprovalrequest',
            index=models.Index(fields=['request_type', 'status'], name='idx_dual_type_status'),
        ),
        migrations.AddIndex(
            model_name='dualapprovalrequest',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_dual_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='emergencycontrol',
            index=models.Index(fields=['control_type', 'is_active'], name='idx_emerg_type_active'),
        ),
        migrations.AddIndex(
            model_name='emergencycontrol',
            index=models.Index(fields=['tenant_id', 'control_type', 'is_active'], name='idx_emerg_tenant_type_active'),
        ),
    ]
