# Generated by Django 6.0.3 on 2026-09-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_control_plane', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminactionlog',
            name='idx_actlog_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='adminsession',
            name='idx_admsess_token',
        ),
        migrations.RemoveIndex(
            model_name='adminsession',
            name='idx_admsess_expires',
        ),
        migrations.RemoveIndex(
            model_name='dualapprovalrequest',
            name='idx_dual_requester',
        ),
    ]
