apiVersion: v1
kind: Secret
metadata:
  name: {{ include "digiland.fullname" . }}-secrets
  labels:
    {{- include "digiland.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | b64enc | quote }}
  CELERY_BROKER_URL: {{ .Values.secrets.celeryBrokerUrl | b64enc | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.stripeSecretKey | b64enc | quote }}
  PAYSTACK_SECRET_KEY: {{ .Values.secrets.paystackSecretKey | b64enc | quote }}
