# Generated by Django 6.0.3 on 2026-03-21 08:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parcel_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('land_use_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Agricultural', 'Agricultural')], max_length=20)),
                ('county', models.CharField(default='Nairobi', max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('land_size', models.DecimalField(decimal_places=4, max_digits=10)),
                ('registered_owner_id', models.CharField(help_text='ID number of registered owner', max_length=100)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Disputed', 'Disputed'), ('Fraudulent', 'Fraudulent')], default='Pending', max_length=20)),
                ('ardhisasa_last_synced', models.DateTimeField(blank=True, null=True)),
                ('current_risk_score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('id_number', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Land_Official', 'Land Official'), ('Admin', 'Admin')], max_length=20)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('gavakonect_verification_id', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Title_Deed', 'Title Deed'), ('ID_Card', 'ID Card'), ('Passport_Photo', 'Passport Photo'), ('Sale_Agreement', 'Sale Agreement')], max_length=20)),
                ('file_url', models.FileField(upload_to='documents/')),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Match', 'Match'), ('Mismatch', 'Mismatch'), ('Forgery_Suspected', 'Forgery Suspected')], default='Pending', max_length=25)),
                ('fraud_flag_notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('land_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.landparcel')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Deposit_Paid', 'Deposit Paid'), ('Under_Verification', 'Under Verification'), ('Completed', 'Completed'), ('Disputed', 'Disputed'), ('Refunded', 'Refunded')], default='Initiated', max_length=20)),
                ('escrow_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_transactions', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_transactions', to=settings.AUTH_USER_MODEL)),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.landparcel')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
