# Generated by Django 6.0.3 on 2026-03-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of the land', null=True, upload_to='land_images/'),
        ),
    ]
