# Generated by Django 6.0.3 on 2026-03-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_landparcel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='listed_by',
            field=models.ForeignKey(blank=True, help_text='The seller who listed this parcel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listed_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
