# Generated by Django 6.0.3 on 2026-03-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_landparcel_listed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landparcel',
            name='verification_status',
            field=models.CharField(choices=[('Awaiting_Documents', 'Awaiting Documents'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Disputed', 'Disputed'), ('Fraudulent', 'Fraudulent')], default='Pending', max_length=20),
        ),
    ]
