# Generated by Django 6.0.3 on 2026-03-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transaction_buyer_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='asking_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Seller's absolute asking price", max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='lowest_negotiable_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hidden bottom limit for auto-negotiation', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('Title_Deed', 'Title Deed'), ('ID_Card', 'ID Card'), ('Passport_Photo', 'Passport Photo'), ('Sale_Agreement', 'Sale Agreement'), ('Spousal_Consent', 'Spousal Consent Affidavit')], max_length=20),
        ),
    ]
