# Generated by Django 6.0.3 on 2026-03-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_landparcel_asking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_accepted',
            field=models.BooleanField(blank=True, help_text='True=buyer confirmed legitimacy, False=buyer disputed/requested refund, None=still in validation window', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_validation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline by which buyer must confirm or disputes ownership. Funds are fully refundable until this date.', null=True),
        ),
    ]
