# Generated by Django 6.0.3 on 2026-03-22 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_buyer_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentKYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_pin', models.CharField(help_text='Kenya Revenue Authority PIN', max_length=20)),
                ('id_number', models.CharField(help_text='National ID or Passport Number', max_length=20)),
                ('id_photo', models.FileField(help_text='Scanned copy of National ID / Passport', upload_to='kyc/id_photos/')),
                ('resume', models.FileField(help_text='Current CV / Resume (PDF)', upload_to='kyc/resumes/')),
                ('certificate_of_good_conduct', models.FileField(help_text='DCI Certificate of Good Conduct (PDF)', upload_to='kyc/conduct_certs/')),
                ('practicing_certificate', models.FileField(blank=True, help_text='LSK / Real Estate Board Practicing Certificate (if applicable)', null=True, upload_to='kyc/practicing_certs/')),
                ('kyc_submitted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.OneToOneField(limit_choices_to={'role': 'Agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
