# Generated by Django 6.0.3 on 2026-03-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_agentrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="land_verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from land verification process", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="land_verification_started",
            field=models.DateTimeField(
                blank=True,
                help_text="When land verification process started",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="land_verified",
            field=models.BooleanField(
                default=False,
                help_text="Whether land location and details have been verified",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_initiated_at",
            field=models.DateTimeField(
                blank=True, help_text="When reversal was initiated", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_initiated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who initiated the reversal",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_reason",
            field=models.TextField(
                blank=True, help_text="Reason for payment reversal", null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_reference",
            field=models.CharField(
                blank=True,
                help_text="Reference number for the reversal transaction",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="verification_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who verified the land details",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Initiated", "Initiated"),
                    ("Deposit_Paid", "Deposit Paid"),
                    ("Under_Verification", "Under Verification"),
                    ("Verification_Hiatus", "Verification Hiatus"),
                    ("Completed", "Completed"),
                    ("Disputed", "Disputed"),
                    ("Refunded", "Refunded"),
                    ("Reversed", "Reversed by Admin"),
                ],
                default="Initiated",
                max_length=20,
            ),
        ),
    ]
