# Generated by Django 6.0.3 on 2026-04-20 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_transaction_land_verification_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="kra_pin",
            field=models.CharField(
                default="",
                help_text="KRA PIN e.g. A123456789B",
                max_length=11,
                validators=[
                    django.core.validators.RegexValidator(
                        message="KRA PIN must be 11 characters: Letter + 9 digits + Letter (e.g. A123456789B).",
                        regex="^[A-Z]\\d{9}[A-Z]$",
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                db_index=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="ID number must be 7, 8, or 9 digits.",
                        regex="^\\d{7,9}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must start with +254 or 0 and have 10 digits total (e.g. +254712345678 or 0712345678).",
                        regex="^(\\+254|0)\\d{9}$",
                    )
                ],
            ),
        ),
    ]
