# Generated by Django 6.0.3 on 2026-04-27 09:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_parcelview_userfavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_joint_purchase",
            field=models.BooleanField(
                default=False, help_text="Whether this is a joint/group purchase"
            ),
        ),
        migrations.CreateModel(
            name="JointBuyerGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Group or chama name (e.g. 'Wanjiku Family Trust')",
                        max_length=200,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("Couple", "Couple"),
                            ("Chama", "Chama / Investment Group"),
                            ("Family", "Family Trust"),
                            ("Investment_Group", "Investment Group"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            (
                                "Joint_Tenancy",
                                "Joint Tenancy (equal shares, right of survivorship)",
                            ),
                            (
                                "Tenancy_In_Common",
                                "Tenancy in Common (specified shares, independently transferable)",
                            ),
                        ],
                        default="Tenancy_In_Common",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "leader",
                    models.ForeignKey(
                        help_text="The registered Buyer who manages this group",
                        limit_choices_to={"role": "Buyer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_joint_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="joint_group",
            field=models.ForeignKey(
                blank=True,
                help_text="The joint buyer group for group purchases",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.jointbuyergroup",
            ),
        ),
        migrations.CreateModel(
            name="JointBuyerMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full legal name as per National ID", max_length=200
                    ),
                ),
                (
                    "id_number",
                    models.CharField(help_text="National ID number", max_length=20),
                ),
                (
                    "kra_pin",
                    models.CharField(
                        help_text="KRA PIN (e.g. A123456789B)", max_length=11
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number for M-PESA payments", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email for notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "share_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ownership share (must total 100% per group)",
                        max_digits=5,
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded drawn signature",
                        null=True,
                    ),
                ),
                ("has_signed", models.BooleanField(default=False)),
                (
                    "is_leader",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this member is the registered group leader",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.jointbuyergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_leader", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="JointPaymentContribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("STK_Pushed", "STK Push Sent"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mpesa_receipt",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions",
                        to="core.jointbuyermember",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="joint_contributions",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
