# Generated by Django 6.0.3 on 2026-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_transaction_is_joint_purchase_jointbuyergroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="buyer_account_type",
            field=models.CharField(
                blank=True,
                choices=[("Individual", "Individual"), ("Joint", "Joint")],
                help_text="Buyer onboarding choice: individual or joint purchase mode.",
                max_length=20,
                null=True,
            ),
        ),
    ]
