# Generated by Django 6.0.3 on 2026-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_user_buyer_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="jointbuyergroup",
            name="bank_account_name",
            field=models.CharField(
                blank=True,
                help_text="Account name as held at the bank",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jointbuyergroup",
            name="bank_account_number",
            field=models.CharField(
                blank=True,
                help_text="Joint bank account number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jointbuyergroup",
            name="bank_branch",
            field=models.CharField(
                blank=True,
                help_text="Branch where the account is held",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jointbuyergroup",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Bank name for the joint account",
                max_length=120,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jointbuyergroup",
            name="preferred_payment_method",
            field=models.CharField(
                choices=[
                    ("M_Pesa_Split", "M-Pesa Split Contributions"),
                    ("Joint_Bank_Account", "Joint Bank Account"),
                    ("Leader_Managed", "Leader Manages Payment"),
                ],
                default="M_Pesa_Split",
                help_text="Preferred payment method for the joint checkout flow.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="bank_account_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="bank_branch",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="bank_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="bank_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="depositor_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="jointpaymentcontribution",
            name="payment_channel",
            field=models.CharField(
                choices=[
                    ("M_Pesa", "M-Pesa STK"),
                    ("Bank_Transfer", "Joint Bank Transfer"),
                ],
                default="M_Pesa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jointpaymentcontribution",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="jointpaymentcontribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("STK_Pushed", "STK Push Sent"),
                    ("Bank_Submitted", "Bank Transfer Submitted"),
                    ("Completed", "Completed"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
