# Generated by Django 6.0.3 on 2026-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_jointbuyergroup_bank_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jointbuyergroup",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    (
                        "Joint_Tenancy",
                        "Joint Tenancy (spouses only or with court leave)",
                    ),
                    (
                        "Tenancy_In_Common",
                        "Tenancy in Common (recommended for most group purchases)",
                    ),
                ],
                default="Tenancy_In_Common",
                max_length=20,
            ),
        ),
    ]
