# Generated by Django 6.0.3 on 2026-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_jointbuyergroup_ownership_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Title_Deed", "Title Deed"),
                    ("ID_Card", "ID Card"),
                    ("Passport_Photo", "Passport Photo"),
                    ("Sale_Agreement", "Sale Agreement"),
                    ("Spousal_Consent", "Spousal Consent Affidavit"),
                    ("Land_Search", "Land Search Certificate"),
                    ("Land_Rates_Clearance", "Land Rates Clearance"),
                    ("Land_Rent_Clearance", "Land Rent Clearance"),
                    ("Survey_Plan", "Survey Plan / Mutation Form"),
                    ("Consent_To_Transfer", "Land Control Board Consent"),
                    ("Stamp_Duty_Receipt", "Stamp Duty Receipt"),
                    ("Valuation_Report", "Valuation Report"),
                ],
                max_length=30,
            ),
        ),
    ]
