# Generated by Django 6.0.3 on 2026-05-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_alter_document_document_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformLegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "content",
                    models.TextField(
                        help_text="Enter the legal document paragraphs here."
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Legal Document",
                "verbose_name_plural": "Legal Documents",
                "ordering": ["title"],
            },
        ),
    ]
