# Generated by Django 6.0.3 on 2026-05-03 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_platformlegaldocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED_FOR_REVIEW", "Flagged for Review"),
                            ("LOCKED", "Locked / Fraud"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "id_number_hash",
                    models.CharField(
                        blank=True, db_index=True, max_length=128, null=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("face_embedding", models.JSONField(blank=True, null=True)),
                ("liveness_score", models.FloatField(default=0.0)),
                (
                    "id_front_image",
                    models.FileField(blank=True, null=True, upload_to="kyc/secure/id/"),
                ),
                (
                    "selfie_image",
                    models.FileField(
                        blank=True, null=True, upload_to="kyc/secure/selfie/"
                    ),
                ),
                ("audit_log", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
