# Generated by Django 6.0.3 on 2026-05-29 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_jointmemberremovalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_hospital',
            field=models.FloatField(default=2.0, help_text='Distance to closest hospital in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_industrial_zone',
            field=models.FloatField(default=8.0, help_text='Distance to closest industrial zone in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_mall',
            field=models.FloatField(default=5.0, help_text='Distance to closest mall in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_road',
            field=models.FloatField(default=0.5, help_text='Distance to closest road in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_school',
            field=models.FloatField(default=1.5, help_text='Distance to closest school in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='dist_to_transport_hub',
            field=models.FloatField(default=3.0, help_text='Distance to closest transport hub in km'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geospatial latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Geospatial longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_diligence_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='include_due_diligence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='include_legal_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='legal_verification_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='platform_service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.CreateModel(
            name='BuyerEngagementSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('View', 'View Listing'), ('Click', 'Click Listing'), ('Favorite', 'Favorite Listing'), ('Inquiry', 'Inquiry/Message'), ('Map_Interaction', 'Map Interaction'), ('Video_Watch', 'Video Watch Time'), ('Offer_Submitted', 'Offer Submitted')], max_length=20)),
                ('value', models.FloatField(default=1.0, help_text='Watch time in seconds or other weight indicator')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_signals', to='core.landparcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BuyerInterestProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Residential', 'Residential Buyer'), ('Agricultural', 'Agricultural Investor'), ('Commercial', 'Commercial Developer'), ('Speculator', 'Speculator'), ('Luxury', 'Luxury Buyer'), ('Diaspora', 'Diaspora Investor')], default='Residential', max_length=30)),
                ('preferred_counties', models.JSONField(blank=True, default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('preferred_acreage_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('preferred_acreage_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('preferred_land_use', models.CharField(blank=True, max_length=20, null=True)),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interest_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('Basic', 'Basic Promotion'), ('Pro', 'Pro Promotion'), ('Elite', 'Elite Promotion')], max_length=20)),
                ('billing_model', models.CharField(choices=[('Daily', 'Pay-per-day'), ('PPC', 'Pay-per-click'), ('PPI', 'Pay-per-impression'), ('Bundle', 'Subscription Bundle')], max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_counties', models.JSONField(blank=True, default=list, help_text='Targeted counties/regions')),
                ('target_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_buyer_intents', models.JSONField(blank=True, default=list, help_text='List of buyer intents targeted')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('views_count', models.IntegerField(default=0)),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('inquiries_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_promotions', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='core.landparcel')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PromotionAnalyticsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Impression', 'Impression'), ('Click', 'Click'), ('Inquiry', 'Inquiry')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('placement_area', models.CharField(blank=True, max_length=50, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.landpromotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
