# Generated by Django 6.0.3 on 2026-05-29 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_landparcel_dist_to_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupAdCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=220)),
                ('popup_type', models.CharField(choices=[('Smart_Recommendation', 'Smart Recommendation'), ('Exit_Intent', 'Exit Intent'), ('Geo_Targeted', 'Geo-Targeted'), ('Urgency', 'Urgency'), ('Behavioral_Retargeting', 'Behavioral Retargeting')], max_length=30)),
                ('billing_model', models.CharField(choices=[('PPV', 'Pay Per View'), ('PPC', 'Pay Per Click'), ('PPL', 'Pay Per Lead'), ('Subscription', 'Premium Subscription'), ('Geo_Exclusive', 'Geo-Exclusive Campaign')], max_length=20)),
                ('headline', models.CharField(max_length=220)),
                ('subheadline', models.TextField(blank=True, null=True)),
                ('cta_text', models.CharField(default='View listing', max_length=80)),
                ('landing_url', models.URLField(blank=True, null=True)),
                ('target_counties', models.JSONField(blank=True, default=list)),
                ('target_locations', models.JSONField(blank=True, default=list)),
                ('target_buyer_categories', models.JSONField(blank=True, default=list)),
                ('target_intent_tags', models.JSONField(blank=True, default=list)),
                ('target_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target_acreage_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('target_acreage_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('travel_radius_km', models.FloatField(default=20.0)),
                ('frequency_cap_per_session', models.PositiveIntegerField(default=1)),
                ('cooldown_minutes', models.PositiveIntegerField(default=45)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('priority_bid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('geo_exclusive', models.BooleanField(default=False)),
                ('seller_verified_only', models.BooleanField(default=True)),
                ('creative_image', models.ImageField(blank=True, null=True, upload_to='popup_ads/images/')),
                ('creative_video_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('revenue_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('impressions_count', models.IntegerField(default=0)),
                ('clicks_count', models.IntegerField(default=0)),
                ('leads_count', models.IntegerField(default=0)),
                ('dismissals_count', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('auction_score', models.FloatField(default=0.0)),
                ('roi_score', models.FloatField(default=0.0)),
                ('last_scored_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_campaigns', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popup_campaigns', to='core.landparcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PopupAdEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Impression', 'Impression'), ('Click', 'Click'), ('Lead', 'Lead'), ('Dismissed', 'Dismissed'), ('Suppressed', 'Suppressed'), ('Exit_Intent', 'Exit Intent')], max_length=20)),
                ('placement_area', models.CharField(blank=True, max_length=50, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('page_context', models.CharField(blank=True, max_length=80, null=True)),
                ('buyer_category', models.CharField(blank=True, max_length=30, null=True)),
                ('county_context', models.CharField(blank=True, max_length=100, null=True)),
                ('intent_score', models.FloatField(default=0.0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('dwell_seconds', models.FloatField(default=0.0)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('conversion_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.popupadcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='popup_ad_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', 'event_type'], name='core_popupa_campaig_c00f95_idx'), models.Index(fields=['placement_area', 'created_at'], name='core_popupa_placeme_9cdaf4_idx'), models.Index(fields=['county_context', 'created_at'], name='core_popupa_county__32e5f2_idx')],
            },
        ),
    ]
