# Generated by Django 6.0.3 on 2026-05-30 08:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_popupadcampaign_popupadevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Basic', 'Basic - Free'), ('Pro', 'Pro - $100/month'), ('Elite', 'Elite - $500/month')], max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tier_level', models.IntegerField(choices=[(0, 'Basic'), (1, 'Pro'), (2, 'Elite')])),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features_json', models.JSONField(default=dict, help_text='Features available in this tier')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Promotion Tiers',
                'ordering': ['tier_level'],
            },
        ),
        migrations.CreateModel(
            name='FraudScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, help_text='0-100 fraud risk score')),
                ('risk_factors', models.JSONField(blank=True, default=list, help_text='List of detected risk factors')),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fraud Scores',
            },
        ),
        migrations.CreateModel(
            name='PromotionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Paused', 'Paused'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(limit_choices_to={'role__in': ['Seller', 'Agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_plan', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.promotiontier')),
            ],
            options={
                'verbose_name_plural': 'Promotion Plans',
            },
        ),
        migrations.CreateModel(
            name='PromotionPlanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.promotionplan')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
            options={
                'verbose_name_plural': 'Promotion Plan Payments',
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('algorithm_type', models.CharField(choices=[('ContentBased', 'Content Based'), ('Collaborative', 'Collaborative'), ('GeoSpatial', 'Geo-Spatial'), ('Trending', 'Trending'), ('Sponsored', 'Sponsored'), ('Hybrid', 'Hybrid')], max_length=30)),
                ('rank', models.IntegerField(help_text='Position in recommendation list')),
                ('score', models.FloatField(default=0, help_text='Recommendation score (0-100)')),
                ('clicked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('inquired', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='User feedback: -1 (bad), 0 (neutral), 1 (good)', null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to='core.landparcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='4% platform service fee', max_digits=12)),
                ('escrow_fee', models.DecimalField(decimal_places=2, default=0, help_text='2% escrow holding fee', max_digits=12)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, help_text='Flat payment processing fee', max_digits=10)),
                ('verification_fee', models.DecimalField(decimal_places=2, default=0, help_text='Optional verification fee', max_digits=12)),
                ('due_diligence_fee', models.DecimalField(decimal_places=2, default=0, help_text='Optional due diligence fee', max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of fees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee', to='core.transaction')),
            ],
            options={
                'verbose_name_plural': 'Service Fees',
            },
        ),
        migrations.CreateModel(
            name='SponsoredAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(default='Basic', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Custom ad title (optional)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Ad description', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='Custom ad image', max_length=500)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Paused', 'Paused'), ('Ended', 'Ended'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('billing_model', models.CharField(choices=[('PayPerDay', 'Pay Per Day'), ('PayPerClick', 'Pay Per Click'), ('PayPerImpression', 'Pay Per Impression'), ('Subscription', 'Subscription Bundle')], default='PayPerDay', max_length=20)),
                ('budget_daily', models.DecimalField(blank=True, decimal_places=2, help_text='Daily budget for this campaign', max_digits=10, null=True)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total campaign budget', max_digits=12, null=True)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('targeting_criteria', models.JSONField(blank=True, default=dict, help_text='Location, budget, buyer type targeting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_ads', to='core.landparcel')),
                ('seller', models.ForeignKey(limit_choices_to={'role__in': ['Seller', 'Agent']}, on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sponsored Ads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Impression', 'Impression'), ('Click', 'Click'), ('Save', 'Save'), ('Inquiry', 'Inquiry/Conversion'), ('Share', 'Share')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_page', models.CharField(blank=True, help_text='homepage, search, recommendations, etc.', max_length=50)),
                ('device_type', models.CharField(blank=True, help_text='mobile, desktop, tablet', max_length=20)),
                ('geolocation', models.JSONField(blank=True, default=dict, help_text='User location at time of engagement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.sponsoredad')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdBillingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Impression', 'Impression'), ('Click', 'Click'), ('Conversion', 'Conversion')], max_length=20)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('billing_status', models.CharField(choices=[('Pending', 'Pending'), ('Billed', 'Billed'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.adengagement')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='core.sponsoredad')),
            ],
            options={
                'verbose_name_plural': 'Ad Billing Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('View', 'Parcel View'), ('SearchImpression', 'Search Result Impression'), ('Click', 'Click Listing'), ('Save', 'Save Favorite'), ('Inquiry', 'Send Inquiry'), ('Share', 'Share Listing'), ('MapInteraction', 'Map Interaction'), ('VideoWatch', 'Video Watch')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='core.landparcel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['parcel', 'timestamp'], name='core_analyt_parcel__65b953_idx'), models.Index(fields=['event_type', 'timestamp'], name='core_analyt_event_t_88cfd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('Verified', 'Verified Listing'), ('LegalChecked', 'Legal Checked'), ('TransactionSuccess', 'Transaction Success'), ('SellerTrusted', 'Trusted Seller')], max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['Agent', 'Admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_badges', to='core.landparcel')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('parcel', 'badge_type')},
            },
        ),
    ]
