# Generated by Django 6.0.5 on 2026-06-03 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auth_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='adbillingevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='adbillingevent',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='adbillingevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adbillingevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adengagement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='adengagement',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='adengagement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adengagement',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentkycapplication',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='agentkycapplication',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='agentkycapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agentkycapplication',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agentrating',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerengagementsignal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='buyerengagementsignal',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='buyerengagementsignal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buyerengagementsignal',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buyerinterestprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='buyerinterestprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='buyerinterestprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudscore',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='fraudscore',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='fraudscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fraudscore',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jointbuyergroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='jointbuyergroup',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='jointbuyergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointbuyergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jointbuyermember',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='jointbuyermember',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='jointbuyermember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointbuyermember',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jointmemberremovalrequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='jointmemberremovalrequest',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='jointmemberremovalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointmemberremovalrequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jointpaymentcontribution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='jointpaymentcontribution',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='jointpaymentcontribution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jointpaymentcontribution',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='kycprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landpromotion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='landpromotion',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='landpromotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='landpromotion',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelview',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='parcelview',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='parcelview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parcelview',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformlegaldocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='platformlegaldocument',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='platformlegaldocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popupadcampaign',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='popupadcampaign',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='popupadcampaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='popupadevent',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='popupadevent',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='popupadevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='popupadevent',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionanalyticslog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='promotionanalyticslog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='promotionanalyticslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='promotionanalyticslog',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='promotionplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionplanpayment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='promotionplanpayment',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='promotionplanpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotiontier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='promotiontier',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='promotiontier',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='searchquerylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='servicefee',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='sponsoredad',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationbadge',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp — null means active record', null=True),
        ),
        migrations.AddField(
            model_name='verificationbadge',
            name='tenant_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True),
        ),
        migrations.AddField(
            model_name='verificationbadge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='verificationbadge',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='buyerinterestprofile',
            index=models.Index(fields=['tenant_id', 'user', 'category'], name='idx_bip_tenant_usr_cat'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant_id', 'land_parcel', 'verification_status'], name='idx_doc_tenant_pcl_vsts'),
        ),
        migrations.AddIndex(
            model_name='landparcel',
            index=models.Index(fields=['tenant_id', 'verification_status', 'county'], name='idx_lp_tenant_vsts_county'),
        ),
        migrations.AddIndex(
            model_name='landparcel',
            index=models.Index(fields=['tenant_id', 'listed_by'], name='idx_lp_tenant_listed_by'),
        ),
        migrations.AddIndex(
            model_name='landparcel',
            index=models.Index(fields=['tenant_id', 'asking_price'], name='idx_lp_tenant_ask_price'),
        ),
        migrations.AddIndex(
            model_name='landparcel',
            index=models.Index(fields=['tenant_id', 'land_use_type', 'county'], name='idx_lp_tenant_lut_county'),
        ),
        migrations.AddIndex(
            model_name='landpromotion',
            index=models.Index(fields=['tenant_id', 'is_active', 'tier'], name='idx_lpromo_tenant_act_tier'),
        ),
        migrations.AddIndex(
            model_name='landpromotion',
            index=models.Index(fields=['tenant_id', 'created_by'], name='idx_lpromo_tenant_crt_by'),
        ),
        migrations.AddIndex(
            model_name='parcelview',
            index=models.Index(fields=['tenant_id', 'user', 'parcel', 'viewed_at'], name='idx_pv_tenant_usr_parcel'),
        ),
        migrations.AddIndex(
            model_name='popupadcampaign',
            index=models.Index(fields=['tenant_id', 'status', 'billing_model'], name='idx_pac_tenant_sts_bill'),
        ),
        migrations.AddIndex(
            model_name='popupadcampaign',
            index=models.Index(fields=['tenant_id', 'created_by'], name='idx_pac_tenant_crt_by'),
        ),
        migrations.AddIndex(
            model_name='servicefee',
            index=models.Index(fields=['tenant_id', 'transaction'], name='idx_sf_tenant_txn'),
        ),
        migrations.AddIndex(
            model_name='sponsoredad',
            index=models.Index(fields=['tenant_id', 'status', 'billing_model'], name='idx_sad_tenant_sts_bill'),
        ),
        migrations.AddIndex(
            model_name='sponsoredad',
            index=models.Index(fields=['tenant_id', 'seller'], name='idx_sad_tenant_seller'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'buyer', 'status'], name='idx_txn_tenant_buyer_sts'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'seller', 'status'], name='idx_txn_tenant_seller_sts'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_txn_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tenant_id', 'created_at'], name='idx_txn_tenant_crt_at'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['tenant_id', 'user', 'parcel'], name='idx_uf_tenant_usr_parcel'),
        ),
    ]
