# Generated by Django 6.0.3 on 2026-06-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_additional_production_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_auditlog_user',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_auditlog_action',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_auditlog_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='idx_auditlog_user_action_ts',
        ),
        migrations.RemoveIndex(
            model_name='jointpaymentcontribution',
            name='idx_jpc_checkout_request_id',
        ),
        migrations.RemoveIndex(
            model_name='jointpaymentcontribution',
            name='idx_jpc_status',
        ),
        migrations.RemoveIndex(
            model_name='jointpaymentcontribution',
            name='idx_jpc_transaction',
        ),
        migrations.RemoveIndex(
            model_name='landparcel',
            name='idx_landparcel_verif_status',
        ),
        migrations.RemoveIndex(
            model_name='landparcel',
            name='idx_landparcel_listed_by',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_message_sender',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_message_receiver',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_message_is_read',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_message_receiver_unread',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='idx_supportticket_user',
        ),
        migrations.RemoveIndex(
            model_name='supportticket',
            name='idx_supportticket_status',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_status',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_buyer',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_seller',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_transaction_created_at',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='idx_user_role',
        ),
        migrations.RemoveIndex(
            model_name='userfavorite',
            name='idx_userfavorite_saved_at',
        ),
    ]
