# Generated by Django 6.0.3 on 2026-07-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_is_onboarded_alter_user_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Agent', 'Agent'), ('Lawyer', 'Lawyer'), ('Land_Official', 'Land Official'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
