# Generated by Django 6.0.3 on 2026-07-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lawyer_lsk_number',
            field=models.CharField(blank=True, help_text='LSK Admission Number of the lawyer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lawyer_name',
            field=models.CharField(blank=True, help_text='Full name of the LSK verified lawyer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lawyer_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded cryptographic signature graphic of the LSK verified lawyer', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lawyer_signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the lawyer signed the transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='contract_agreed',
            field=models.BooleanField(default=False, help_text='Has the contract been fully signed by all parties?'),
        ),
    ]
