# Generated by Django 6.0.3 on 2026-07-22 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_transaction_lawyer_lsk_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_constituency',
            field=models.CharField(blank=True, help_text='Agent operating constituency used for commission routing.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_county',
            field=models.CharField(blank=True, help_text='Agent operating county used for commission routing.', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PurchaseCommission',
            fields=[
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Organization tenant ID for row-level security isolation', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_joint_purchase', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Open', 'Open - Awaiting Agent'), ('Accepted', 'Accepted by Agent'), ('Documents_Review', 'Step 1 - Document Review'), ('Lawyer_Verification', 'Step 2 - Lawyer Verification'), ('Site_Visit_Scheduled', 'Step 3 - Site Visit Scheduled'), ('Site_Visit_Complete', 'Step 4 - Site Visit Complete'), ('Closing', 'Step 5 - Closing & Payment'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Open', max_length=32)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('documents_reviewed', models.BooleanField(default=False)),
                ('documents_review_note', models.TextField(blank=True)),
                ('documents_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lawyer_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('lawyer_verified', models.BooleanField(blank=True, null=True)),
                ('lawyer_verification_note', models.TextField(blank=True)),
                ('lawyer_verified_at', models.DateTimeField(blank=True, null=True)),
                ('site_visit_date', models.DateTimeField(blank=True, null=True)),
                ('site_visit_location', models.CharField(blank=True, max_length=500)),
                ('site_visit_notes', models.TextField(blank=True)),
                ('site_visit_complete', models.BooleanField(default=False)),
                ('site_visit_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('target_county', models.CharField(db_index=True, max_length=100)),
                ('target_constituency', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp - null means active record', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_commissions', to=settings.AUTH_USER_MODEL)),
                ('assigned_lawyer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Lawyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_commissions', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_commissions', to=settings.AUTH_USER_MODEL)),
                ('joint_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_requests', to='core.jointbuyergroup')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='core.landparcel')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='core.transaction')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Last user who modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='idx_comm_tenant_status'), models.Index(fields=['tenant_id', 'target_county', 'target_constituency'], name='idx_comm_tenant_region'), models.Index(fields=['tenant_id', 'buyer', 'status'], name='idx_comm_tenant_buyer_status')],
            },
        ),
    ]
