# Generated by Django 6.0.3 on 2026-07-30 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_agent_constituency_user_agent_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_access_pin_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='DocumentAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_auth_token', models.CharField(blank=True, max_length=64)),
                ('accessor_auth_token', models.CharField(blank=True, max_length=64)),
                ('seller_signed_at', models.DateTimeField(blank=True, null=True)),
                ('accessor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('access_granted', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to=settings.AUTH_USER_MODEL)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_grants', to='core.purchasecommission')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to='core.landparcel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parcel', 'accessor', 'access_granted'], name='core_docume_parcel__20dc19_idx')],
            },
        ),
        migrations.CreateModel(
            name='LawyerPostTransactionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(choices=[('lodge_caution', 'Lodge Registry Caution/Caveat'), ('lcb_consent', 'Obtain Land Control Board Consent'), ('rates_clearance', 'Obtain Land Rates Clearance Certificate'), ('rent_clearance', 'Obtain Land Rent Clearance'), ('stamp_duty', 'Calculate & Pay Stamp Duty'), ('submit_transfer', 'Submit Transfer Documents to Registry'), ('title_handover', 'Final Title Deed Handover to Buyer')], max_length=40)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lawyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_transaction_tasks', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_post_transaction_tasks', to='core.transaction')),
            ],
            options={
                'ordering': ['transaction', 'task_key'],
                'unique_together': {('transaction', 'task_key')},
            },
        ),
    ]
