# Generated by Django 6.0.3 on 2026-07-31 05:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_document_access_pin_hash_documentaccessgrant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyerposttransactiontask',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='documentaccessgrant',
            name='core_docume_parcel__20dc19_idx',
        ),
        migrations.RemoveField(
            model_name='lawyerposttransactiontask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='lawyerposttransactiontask',
            name='evidence_url',
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='accessor_auth_signature',
            field=models.TextField(blank=True, help_text='Cryptographic signature/hash from lawyer or agent confirming request', null=True),
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller authorizing access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='seller_auth_signature',
            field=models.TextField(blank=True, help_text='Cryptographic signature/hash from the seller authorizing access', null=True),
        ),
        migrations.AddField(
            model_name='lawyerposttransactiontask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lawyerposttransactiontask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyerposttransactiontask',
            name='reference_number',
            field=models.CharField(blank=True, help_text='e.g. LCB Consent Ref, Stamp Duty Receipt No.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lawyerposttransactiontask',
            name='task_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='accessor',
            field=models.ForeignKey(blank=True, help_text='Lawyer or Agent requesting access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_grants', to='core.purchasecommission'),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.landparcel'),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conveyancing_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='task_key',
            field=models.CharField(choices=[('lodge_caution', 'Lodge Registry Caution/Caveat (within 48 hours)'), ('lcb_consent', 'Obtain Land Control Board (LCB) Consent'), ('rates_clearance', 'Obtain County Land Rates Clearance Certificate'), ('rent_clearance', 'Obtain Ministry Land Rent Clearance Certificate'), ('stamp_duty', 'Calculate & Pay Stamp Duty to KRA'), ('submit_transfer', 'Submit Transfer Documents to Land Registry'), ('title_handover', 'Final Title Deed Handover to Buyer')], default='lodge_caution', max_length=50),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_transaction_tasks', to='core.transaction'),
        ),
        migrations.AddIndex(
            model_name='documentaccessgrant',
            index=models.Index(fields=['parcel', 'access_granted'], name='idx_dag_parcel_grant'),
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='accessor_auth_token',
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='seller_auth_token',
        ),
    ]
