# Generated by Django 6.0.3 on 2026-08-03 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_lawyerposttransactiontask_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticDocumentReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('Title_Deed', 'Title Deed'), ('ID_Card', 'National ID Card'), ('Passport_Photo', 'Passport Photo'), ('Spousal_Consent', 'Spousal Consent'), ('Search_Certificate', 'Official Land Search Certificate'), ('Land_Rates_Clearance', 'Land Rates Clearance')], db_index=True, max_length=50)),
                ('issuing_authority', models.CharField(default='Ministry of Lands', max_length=150)),
                ('version_label', models.CharField(default='v1.0', max_length=50)),
                ('layout_structure_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('required_seal_features', models.JSONField(blank=True, default=dict, help_text='Expected stamp, seal, and header features')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='authentic_references/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['doc_type', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DOCS_SUBMITTED', 'Documents Submitted'), ('AI_VERIFYING', 'AI Verification In Progress'), ('AI_REJECTED', 'AI Verification Failed'), ('AI_APPROVED', 'AI Verification Passed'), ('AGENT_JOB_POSTED', 'Agent Job Posted'), ('AGENT_ASSIGNED', 'Agent Assigned'), ('AWAITING_SELLER_ACCESS_GRANT', 'Awaiting Seller Access Grant'), ('AGENT_VERIFYING', 'Agent Manual Verification In Progress'), ('AGENT_REJECTED', 'Agent Rejected'), ('AGENT_APPROVED', 'Agent Approved (Unlocked for Buyers)'), ('BUYER_OFFER_RECEIVED', 'Buyer Offer Received'), ('LAWYER_REVIEW', 'Lawyer Review In Progress'), ('LAWYER_APPROVED', 'Lawyer Approved'), ('PURCHASE_FINALIZED', 'Purchase Finalized'), ('AGENT_RELEASED', 'Agent Released'), ('Awaiting_Documents', 'Awaiting Documents'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Disputed', 'Disputed'), ('Fraudulent', 'Fraudulent')], default='Pending', max_length=50),
        ),
    ]
