# Generated by Django 6.0.3 on 2026-08-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_authenticdocumentreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='agent_checkin_notes',
            field=models.JSONField(blank=True, default=list, help_text='Log of weekly check-in notes submitted by assigned agent'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='ai_discrepancy_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of document discrepancy flags detected by AI'),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='ai_verification_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI document authenticity score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='assignment_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry date for agent exclusivity lock (default 30 days)', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='job_expires_at',
            field=models.DateTimeField(blank=True, help_text='Expiry date for agent job board listing (default 7 days)', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='job_posted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when job was posted to regional agents', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='last_agent_checkin_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of agent's last weekly check-in", null=True),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DOCS_SUBMITTED', 'Documents Submitted'), ('AI_VERIFYING', 'AI Verification In Progress'), ('AI_REJECTED', 'AI Verification Failed'), ('AI_APPROVED', 'AI Verification Passed'), ('AGENT_JOB_POSTED', 'Agent Job Posted'), ('AGENT_ASSIGNED', 'Agent Assigned'), ('AWAITING_SELLER_ACCESS_GRANT', 'Awaiting Seller Access Grant'), ('AGENT_VERIFYING', 'Agent Manual Verification In Progress'), ('AGENT_REJECTED', 'Agent Rejected'), ('ADMIN_ESCALATED', 'Admin Escalated Review'), ('AGENT_APPROVED', 'Agent Approved (Unlocked for Buyers)'), ('BUYER_OFFER_RECEIVED', 'Buyer Offer Received'), ('LAWYER_REVIEW', 'Lawyer Review In Progress'), ('LAWYER_APPROVED', 'Lawyer Approved'), ('PURCHASE_FINALIZED', 'Purchase Finalized'), ('AGENT_RELEASED', 'Agent Released'), ('Awaiting_Documents', 'Awaiting Documents'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Disputed', 'Disputed'), ('Fraudulent', 'Fraudulent')], default='Pending', max_length=50),
        ),
    ]
