# Generated by Django 6.0.3 on 2026-08-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_landparcel_agent_checkin_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyerposttransactiontask',
            options={'ordering': ['transaction', 'task_key']},
        ),
        migrations.RemoveIndex(
            model_name='documentaccessgrant',
            name='idx_dag_parcel_grant',
        ),
        migrations.RenameField(
            model_name='lawyerposttransactiontask',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='lawyerposttransactiontask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lawyerposttransactiontask',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='lawyerposttransactiontask',
            name='task_name',
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='accessor_auth_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='documentaccessgrant',
            name='seller_auth_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lawyerposttransactiontask',
            name='evidence_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='accessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='commission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_grants', to='core.purchasecommission'),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentaccessgrant',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_grants', to='core.landparcel'),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='lawyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_transaction_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='task_key',
            field=models.CharField(choices=[('lodge_caution', 'Lodge Registry Caution/Caveat'), ('lcb_consent', 'Obtain Land Control Board Consent'), ('rates_clearance', 'Obtain Land Rates Clearance Certificate'), ('rent_clearance', 'Obtain Land Rent Clearance'), ('stamp_duty', 'Calculate & Pay Stamp Duty'), ('submit_transfer', 'Submit Transfer Documents to Registry'), ('title_handover', 'Final Title Deed Handover to Buyer')], max_length=40),
        ),
        migrations.AlterField(
            model_name='lawyerposttransactiontask',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_post_transaction_tasks', to='core.transaction'),
        ),
        migrations.AddIndex(
            model_name='documentaccessgrant',
            index=models.Index(fields=['parcel', 'accessor', 'access_granted'], name='core_docume_parcel__20dc19_idx'),
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='accessor_auth_signature',
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='granted_at',
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='documentaccessgrant',
            name='seller_auth_signature',
        ),
    ]
