# Generated by Django 6.0.3 on 2026-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_verificationdocumentrequirement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='pre_screened_at',
            field=models.DateTimeField(blank=True, help_text='When parcel passed Phase 1 pre-screening', null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='verification_level',
            field=models.CharField(blank=True, choices=[('NONE', 'No Verification'), ('PRE_SCREENED', 'Digiland Pre-Screened'), ('VERIFIED', 'Digiland Verified'), ('VERIFIED_WITH_CONDITIONS', 'Verified with Conditions')], help_text='Current verification level from the verification engine', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='verification_phase',
            field=models.CharField(blank=True, choices=[('PHASE_1', 'Pre-Interest Screening'), ('PHASE_2', 'Interest-Triggered Due Diligence')], help_text='Current verification phase for this parcel', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='landparcel',
            name='verified_for_transaction_at',
            field=models.DateTimeField(blank=True, help_text='When parcel passed Phase 2 full verification', null=True),
        ),
        migrations.AlterField(
            model_name='landparcel',
            name='verification_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DOCS_SUBMITTED', 'Documents Submitted'), ('AI_VERIFYING', 'AI Verification In Progress'), ('AI_REJECTED', 'AI Verification Failed'), ('AI_APPROVED', 'AI Verification Passed'), ('AGENT_JOB_POSTED', 'Agent Job Posted'), ('AGENT_ASSIGNED', 'Agent Assigned'), ('AWAITING_SELLER_ACCESS_GRANT', 'Awaiting Seller Access Grant'), ('AGENT_VERIFYING', 'Agent Manual Verification In Progress'), ('AGENT_REJECTED', 'Agent Rejected'), ('ADMIN_ESCALATED', 'Admin Escalated Review'), ('AGENT_APPROVED', 'Agent Approved (Unlocked for Buyers)'), ('BUYER_OFFER_RECEIVED', 'Buyer Offer Received'), ('LAWYER_REVIEW', 'Lawyer Review In Progress'), ('LAWYER_APPROVED', 'Lawyer Approved'), ('PURCHASE_FINALIZED', 'Purchase Finalized'), ('AGENT_RELEASED', 'Agent Released'), ('PRE_SCREENED', 'Digiland Pre-Screened'), ('VERIFIED_FOR_TRANSACTION', 'Verified for Transaction'), ('Awaiting_Documents', 'Awaiting Documents'), ('Pending', 'Pending'), ('Verified', 'Verified'), ('Disputed', 'Disputed'), ('Fraudulent', 'Fraudulent')], default='Pending', max_length=50),
        ),
    ]
