# Generated by Django 6.0.3 on 2026-08-30 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_verification_fields_to_landparcel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepredictionlog',
            name='predicted_price_per_acre',
        ),
        migrations.AlterField(
            model_name='pricepredictionlog',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, help_text='Tenant isolation ID', null=True)),
                ('account_type', models.CharField(choices=[('INDIVIDUAL', 'Individual Account'), ('JOINT', 'Human Joint Account'), ('ORGANIZATION', 'Organizational Account')], db_index=True, default='INDIVIDUAL', max_length=20)),
                ('purpose', models.CharField(choices=[('BUY', 'Buyer'), ('SELL', 'Seller'), ('BOTH', 'Buyer & Seller')], db_index=True, default='BUY', max_length=10)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Individual Person'), ('FAMILY', 'Family / Relatives'), ('CHAMA', 'Chama / Investment Group'), ('FRIENDS', 'Friends / Private Group'), ('BUSINESS_PARTNERS', 'Business Partners'), ('JOINT_INVESTMENT', 'Joint Investment Group'), ('COMPANY', 'Company / Corporate Entity'), ('GOVERNMENT', 'Government Entity / Ministry / Agency'), ('INSTITUTION', 'Institution / Educational / Religious'), ('NGO', 'NGO / Non-Profit Organization'), ('SACCO', 'SACCO / Cooperative Society'), ('COOPERATIVE', 'Cooperative Society'), ('BANK', 'Bank / Financial Institution'), ('ESTATE', 'Estate / Succession / Legal Representative'), ('OTHER', 'Other Legal Entity')], db_index=True, default='PERSON', max_length=30)),
                ('display_name', models.CharField(help_text="Public or group name (e.g. 'Umoja Investment Chama')", max_length=255)),
                ('legal_name', models.CharField(blank=True, help_text='Registered legal company or group name', max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Official registration number (e.g. CPR/2026/01)', max_length=100, null=True)),
                ('tax_id_or_kra_pin', models.CharField(blank=True, help_text='KRA PIN for corporate/group tax filing', max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_VERIFICATION', 'Pending Verification'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=25)),
                ('governance_rule', models.CharField(choices=[('SIMPLE_MAJORITY', 'Simple Majority (>50%)'), ('TWO_THIRDS', 'Two-Thirds (≥66.7%)'), ('UNANIMOUS', 'Unanimous (100%)'), ('MANAGER_ONLY', 'Manager / Primary Rep Sole Authority')], default='SIMPLE_MAJORITY', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_accounts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_state', models.JSONField(blank=True, default=dict)),
                ('new_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.account')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AccountInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('invite_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('invitee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('invitee_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('invitee_name', models.CharField(blank=True, max_length=200, null=True)),
                ('proposed_role', models.CharField(default='MEMBER', max_length=35)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.account')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_account_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('BUYER_TEAM_MANAGER', 'Buyer Team Manager'), ('SELLER_TEAM_MANAGER', 'Seller Team Manager'), ('CO_BUYER', 'Co-Buyer / Member'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer'), ('FINANCIAL_CONTRIBUTOR', 'Financial Contributor'), ('PRIMARY_REPRESENTATIVE', 'Primary Representative'), ('AUTHORIZED_REPRESENTATIVE', 'Authorized Representative'), ('TRANSACTION_OFFICER', 'Transaction Officer'), ('FINANCE_OFFICER', 'Finance Officer'), ('LEGAL_REPRESENTATIVE', 'Legal Representative')], db_index=True, default='MEMBER', max_length=35)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INVITED', 'Invited / Pending Acceptance'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], db_index=True, default='ACTIVE', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('share_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Agreed internal contribution/share percentage (0-100)', max_digits=5)),
                ('is_account_leader', models.BooleanField(default=False, help_text='True for Buyer Team Manager or Seller Team Manager (renders Digital Crown)')),
                ('custom_permissions', models.JSONField(blank=True, default=list, help_text='Explicit granted permission codes')),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.account')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_member_invitations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_account_leader', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('decision_type', models.CharField(choices=[('PURCHASE_PROPOSAL', 'Purchase Proposal / Offer Authorization'), ('DUE_DILIGENCE_INITIATION', 'Initiate Due Diligence Request'), ('MEMBER_REMOVAL', 'Propose Member Removal'), ('CHANGE_MANAGER', 'Change Team Manager / Leadership Succession'), ('CLOSE_ACCOUNT', 'Close Account / Liquidation'), ('SALE_AUTHORIZATION', 'Authorize Property Listing / Sale'), ('EXPENSE_PAYMENT', 'Authorize Payment / Escrow Release'), ('CUSTOM_PROPOSAL', 'Custom Group Proposal')], db_index=True, max_length=35)),
                ('title', models.CharField(max_length=255)),
                ('proposal_text', models.TextField()),
                ('proposed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('approval_rule', models.CharField(choices=[('SIMPLE_MAJORITY', 'Simple Majority (>50%)'), ('TWO_THIRDS', 'Two-Thirds Majority (≥66.7%)'), ('UNANIMOUS', 'Unanimous (100%)'), ('ALL_LEGAL_OWNERS', 'All Registered Legal Owners Must Approve')], default='SIMPLE_MAJORITY', max_length=25)),
                ('required_vote_count', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Voting Open'), ('APPROVED', 'Approved (Threshold Met)'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Voting Window Expired'), ('CANCELLED', 'Cancelled by Proposer'), ('EXECUTED', 'Executed / Completed'), ('LEGAL_HOLD', 'Legal Authorization Incomplete / Statutory Consent Missing')], db_index=True, default='ACTIVE', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_decisions', to=settings.AUTH_USER_MODEL)),
                ('land_parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_decisions', to='core.landparcel')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_decisions', to='core.transaction')),
                ('target_member', models.ForeignKey(blank=True, help_text='Target of member removal or role change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_decisions', to='core.accountmember')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('APPROVE', 'Approve / Yes'), ('REJECT', 'Reject / No'), ('REQUEST_DISCUSSION', 'Request Discussion / Hold')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('account_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_votes', to='core.accountmember')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.accountdecision')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('full_legal_name', models.CharField(help_text='Full legal name as recorded on Title Deed / Certificate of Lease', max_length=255)),
                ('id_number_or_reg', models.CharField(help_text='National ID, Alien ID, or Company Reg No.', max_length=100)),
                ('kra_pin', models.CharField(blank=True, help_text='KRA PIN of the legal owner', max_length=50, null=True)),
                ('ownership_structure', models.CharField(choices=[('SOLE_OWNERSHIP', 'Sole Ownership'), ('JOINT_TENANCY', 'Joint Tenancy (Spouses / Equal Right of Survivorship)'), ('TENANCY_IN_COMMON', 'Tenancy in Common (Defined Distinct Percentage Shares)'), ('CORPORATE_ENTITY', 'Corporate / Company Title Ownership'), ('TRUST_OWNERSHIP', 'Trust Ownership / Family Trust'), ('ESTATE_SUCCESSION', 'Estate / Succession (Letters of Administration)'), ('GOVERNMENT_PUBLIC', 'Public / Government Custody'), ('CUSTOMARY_COMMUNITY', 'Community / Customary Title')], default='SOLE_OWNERSHIP', max_length=30)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Legal title ownership percentage (1-100)', max_digits=5)),
                ('is_mandatory_signatory', models.BooleanField(default=True, help_text="Whether this owner's explicit signature/consent is required for transactions")),
                ('legal_verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified / Draft'), ('DOCS_SUBMITTED', 'Documents Submitted for Verification'), ('LAWYER_VERIFIED', 'Verified by LSK Advocate / Lawyer'), ('DISPUTED', 'Disputed / Encumbrance / Caveat Found'), ('REJECTED', 'Legal Verification Failed')], db_index=True, default='UNVERIFIED', max_length=25)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_property_holdings', to='core.account')),
                ('land_parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_owners', to='core.landparcel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updates', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_property_holdings', to=settings.AUTH_USER_MODEL)),
                ('verified_by_lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyer_verified_owners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ownership_percentage', 'full_legal_name'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'purpose'], name='idx_acc_type_purpose'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['entity_type', 'status'], name='idx_acc_entity_status'),
        ),
        migrations.AddIndex(
            model_name='accountauditevent',
            index=models.Index(fields=['account', 'timestamp'], name='idx_acclog_acc_time'),
        ),
        migrations.AddIndex(
            model_name='accountauditevent',
            index=models.Index(fields=['action', 'timestamp'], name='idx_acclog_act_time'),
        ),
        migrations.AddIndex(
            model_name='accountmember',
            index=models.Index(fields=['account', 'status'], name='idx_accmem_acc_status'),
        ),
        migrations.AddIndex(
            model_name='accountmember',
            index=models.Index(fields=['user', 'status'], name='idx_accmem_user_status'),
        ),
        migrations.AddIndex(
            model_name='accountdecision',
            index=models.Index(fields=['account', 'status'], name='idx_dec_acc_status'),
        ),
        migrations.AddIndex(
            model_name='accountdecision',
            index=models.Index(fields=['decision_type', 'status'], name='idx_dec_type_status'),
        ),
        migrations.AlterUniqueTogether(
            name='decisionvote',
            unique_together={('decision', 'voter')},
        ),
        migrations.AddIndex(
            model_name='propertyowner',
            index=models.Index(fields=['land_parcel', 'legal_verification_status'], name='idx_propown_prop_status'),
        ),
    ]
