# Generated by Django 6.0.3 on 2026-09-01 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_payment_and_coordination_fields(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    ServiceFee = apps.get_model('core', 'ServiceFee')
    
    for tx in Transaction.objects.all():
        updated = False
        if tx.escrow_reference and not tx.payment_reference:
            tx.payment_reference = tx.escrow_reference
            updated = True
        if tx.escrow_fee and not tx.coordination_fee:
            tx.coordination_fee = tx.escrow_fee
            updated = True
        if updated:
            tx.save(update_fields=['payment_reference', 'coordination_fee'])

    for sf in ServiceFee.objects.all():
        if sf.escrow_fee and not sf.coordination_fee:
            sf.coordination_fee = sf.escrow_fee
            sf.save(update_fields=['coordination_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_conversation_notification_security_models'),
    ]


    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='coordination_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2% transaction & verification coordination fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='coordination_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Platform transaction & verification coordination fee', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Confirmed payment reference from provider (e.g. M-Pesa receipt, bank ref)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy fee column preserved for historical records', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='escrow_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Legacy fee column preserved for historical records', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='escrow_reference',
            field=models.CharField(blank=True, help_text='Legacy reference column preserved for historical records', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Initiated', 'Initiated'), ('Deposit_Paid', 'Deposit Paid'), ('Payment_Confirmed', 'Payment Confirmed'), ('Under_Verification', 'Under Verification'), ('Verification_Hiatus', 'Verification Hiatus'), ('Completed', 'Completed'), ('Disputed', 'Disputed'), ('Refunded', 'Refunded'), ('Reversed', 'Reversed by Admin')], default='Initiated', max_length=20),
        ),
        migrations.CreateModel(
            name='ParcelTrustProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_identity_verified', models.BooleanField(default=False)),
                ('title_document_reviewed', models.BooleanField(default=False)),
                ('land_records_submitted', models.BooleanField(default=False)),
                ('ai_screening_completed', models.BooleanField(default=False)),
                ('physical_assessment_completed', models.BooleanField(default=False)),
                ('surveyor_verification_completed', models.BooleanField(default=False)),
                ('advocate_review_completed', models.BooleanField(default=False)),
                ('buyer_interest_received', models.BooleanField(default=False)),
                ('payment_confirmation_recorded', models.BooleanField(default=False)),
                ('stage_a_pre_interest_passed', models.BooleanField(default=False, help_text='Stage A: Pre-interest screening checks completed')),
                ('stage_b_due_diligence_passed', models.BooleanField(default=False, help_text='Stage B: Post-interest professional due diligence completed')),
                ('risk_rating', models.CharField(choices=[('LOW_RISK', 'Low Risk - Verified Records'), ('STANDARD', 'Standard - In Review'), ('NEEDS_ATTENTION', 'Needs Attention - Discrepancies Found'), ('HIGH_RISK', 'High Risk - Unverified / Inconsistent')], default='STANDARD', max_length=20)),
                ('summary_notes', models.TextField(blank=True, default='')),
                ('disclaimer', models.TextField(default='DigiLand performs structured verification and provides transaction records designed to reduce avoidable risks. Verification reduces risk but does not constitute a state-guaranteed title or absolute guarantee against unrecorded encumbrances.', help_text='Standard legal disclaimer')),
                ('last_evaluated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='core.landparcel')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('DISPUTE_OPENED', 'Dispute Opened'), ('EVIDENCE_REQUESTED', 'Evidence Requested'), ('PARTIES_NOTIFIED', 'Parties Notified'), ('DOCUMENTS_REVIEWED', 'Documents Under Review'), ('STAFF_ASSESSMENT', 'Staff Assessment in Progress'), ('RESOLUTION_PENDING', 'Resolution / Referral Pending'), ('CASE_CLOSED', 'Case Closed')], db_index=True, default='DISPUTE_OPENED', max_length=30)),
                ('outcome', models.CharField(choices=[('PENDING', 'Investigation In Progress'), ('RESOLVED_BETWEEN_PARTIES', 'Resolved Directly Between Parties'), ('SELLER_ACTION_REQUIRED', 'Seller Action Required'), ('BUYER_ACTION_REQUIRED', 'Buyer Action Required'), ('ADDITIONAL_VERIFICATION_REQUIRED', 'Additional Verification Required'), ('LEGAL_REVIEW_RECOMMENDED', 'Professional / Legal Review Recommended'), ('TRANSACTION_CANCELLED', 'Transaction Cancelled by Mutual Agreement'), ('REFERRED_TO_AUTHORITY', 'Referred to Relevant Authority / Legal Counsel'), ('CLOSED_NO_ACTION', 'Closed Without Action')], default='PENDING', max_length=40)),
                ('claim_summary', models.TextField(help_text='Detailed statement of the issue or dispute')),
                ('evidence_requested', models.TextField(blank=True, default='', help_text='Documents or items requested from parties')),
                ('evidence_submitted', models.JSONField(blank=True, default=list, help_text='List of submitted evidence artifacts with timestamps')),
                ('staff_assessment_notes', models.TextField(blank=True, default='', help_text='Internal staff notes and observations')),
                ('resolution_summary', models.TextField(blank=True, default='', help_text='Final case resolution or referral notes')),
                ('disclaimer', models.TextField(default='DigiLand records dispute evidence and facilitates structured case review between parties. DigiLand does not hold customer funds and does not act as a judicial court or financial regulator.', help_text='Statutory non-custodial disclaimer')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_cases', to='core.landparcel')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respondent_disputes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_cases', to='core.transaction')),
            ],
            options={
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['case_number'], name='idx_dsp_case_num'), models.Index(fields=['transaction', 'status'], name='idx_dsp_txn_status'), models.Index(fields=['status', 'outcome'], name='idx_dsp_status_out')],
            },
        ),
        migrations.CreateModel(
            name='ParcelVerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_layer', models.CharField(choices=[('IDENTITY', 'Seller Identity & KYC'), ('OWNERSHIP_DOCS', 'Title / Ownership Documentation'), ('LAND_RECORDS', 'Land Registry Documentation Completeness'), ('AI_DOCUMENT_SCREENING', 'AI Document Screening & Discrepancy Detection'), ('PHYSICAL_ASSESSMENT', 'Field Agent Physical Site Assessment'), ('SURVEY_VERIFICATION', 'Licensed Land Surveyor Boundary & Beacon Check'), ('LEGAL_REVIEW', 'LSK Advocate Conveyancing & Legal Due Diligence'), ('TRANSACTION_STATUS', 'Buyer Interest & Transaction Agreement'), ('PAYMENT_CONFIRMATION', 'Payment Provider Confirmation Evidence')], db_index=True, max_length=40)),
                ('stage', models.CharField(choices=[('STAGE_A_PRE_INTEREST', 'Stage A: Pre-Interest Verification'), ('STAGE_B_INTEREST_TRIGGERED', 'Stage B: Transaction / Interest Due Diligence')], default='STAGE_A_PRE_INTEREST', max_length=30)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('AI_VERIFIED', 'AI Verified'), ('AI_FLAGGED', 'AI Flagged (Discrepancies Detected)'), ('REQUIRES_HUMAN_REVIEW', 'Requires Human Professional Review'), ('UNABLE_TO_VERIFY', 'Unable to Verify'), ('SUSPICIOUS', 'Suspicious / High Risk'), ('HUMAN_VERIFIED', 'Human Professional Verified'), ('REJECTED', 'Rejected / Failed Verification')], default='NOT_STARTED', max_length=30)),
                ('what_checked', models.CharField(help_text='Specific check performed, e.g. National ID match, Beacon 14/A coordinates', max_length=255)),
                ('evaluator_role', models.CharField(choices=[('AUTOMATED_AI', 'Automated AI Verification Engine'), ('STAFF_REVIEWER', 'DigiLand Staff Reviewer'), ('FIELD_AGENT', 'Licensed Field Agent'), ('LICENSED_SURVEYOR', 'ISLK Licensed Land Surveyor'), ('ADVOCATE', 'High Court Advocate / Conveyancer'), ('REGISTRY_OFFICE', 'Ministry of Lands / Ardhisasa Official Process')], default='AUTOMATED_AI', max_length=30)),
                ('is_automated', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, default='', help_text='Document ID, survey report ID, or external verification hash', max_length=255)),
                ('findings', models.JSONField(blank=True, default=dict, help_text='Structured findings, measurements, or confidence metrics')),
                ('limitations_disclaimer', models.TextField(default='This check is designed to reduce avoidable risk. It does not replace official government registry guarantees or statutory due diligence.', help_text='Clear limitations of this specific check')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='core.landparcel')),
                ('who_checked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage', 'verification_layer'],
                'indexes': [models.Index(fields=['parcel', 'verification_layer'], name='idx_vrf_parcel_layer'), models.Index(fields=['parcel', 'status'], name='idx_vrf_parcel_status')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_provider', models.CharField(choices=[('MPESA', 'M-Pesa Daraja'), ('BANK_TRANSFER', 'Bank Wire / RTGS'), ('STRIPE', 'Card / Stripe'), ('DIRECT_SETTLEMENT', 'Direct Party Settlement')], default='MPESA', max_length=50)),
                ('provider_reference', models.CharField(blank=True, help_text='M-Pesa receipt, bank reference, or provider confirmation ID', max_length=100, null=True)),
                ('digiland_reference', models.CharField(db_index=True, help_text='Unique DigiLand transaction reference', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_status', models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('PENDING_CONFIRMATION', 'Pending Provider Confirmation'), ('CONFIRMED', 'Payment Confirmed by Provider'), ('FAILED', 'Payment Failed'), ('REVERSED', 'Payment Reversal Recorded'), ('CANCELLED', 'Payment Cancelled')], db_index=True, default='INITIATED', max_length=30)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_metadata', models.JSONField(blank=True, default=dict, help_text='Raw provider callback evidence, IPN headers, receipt tokens (no wallet balance)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='core.landparcel')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='core.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['digiland_reference'], name='idx_pmt_dgl_ref'), models.Index(fields=['provider_reference'], name='idx_pmt_prov_ref'), models.Index(fields=['transaction', 'payment_status'], name='idx_pmt_txn_status'), models.Index(fields=['payer', 'payment_status'], name='idx_pmt_payer_status')],
            },
        ),
        migrations.CreateModel(
            name='TransactionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_code', models.CharField(choices=[('PARCEL_LISTED', '1. Parcel Listed'), ('SELLER_IDENTITY_VERIFIED', '2. Seller Identity Verified'), ('PARCEL_DOCS_SUBMITTED', '3. Parcel Documents Submitted'), ('INITIAL_SCREENING_COMPLETED', '4. Initial Document Screening Completed'), ('PARCEL_LISTED_FOR_BUYERS', '5. Parcel Listed for Buyers'), ('BUYER_EXPRESSES_INTEREST', '6. Buyer Expresses Interest'), ('PROFESSIONAL_VERIFICATION_INITIATED', '7. Professional Verification Initiated'), ('SURVEY_VERIFICATION', '8. Survey Verification'), ('PHYSICAL_SITE_ASSESSMENT', '9. Physical Site Assessment'), ('LEGAL_DUE_DILIGENCE', '10. Legal Due Diligence'), ('TRANSACTION_AGREEMENT', '11. Buyer/Seller Transaction Agreement'), ('PAYMENT_INITIATED', '12. Payment Initiated'), ('PAYMENT_CONFIRMED', '13. Payment Confirmed by Provider'), ('OWNERSHIP_TRANSFER_PROCESS', '14. Ownership Transfer Process'), ('TRANSACTION_COMPLETED', '15. Transaction Completed')], db_index=True, max_length=50)),
                ('sequence_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('FLAGGED', 'Flagged with Conditions')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('responsible_role', models.CharField(blank=True, default='', max_length=50)),
                ('evidence_data', models.JSONField(blank=True, default=dict, help_text='Audit evidence, document links, or receipt references')),
                ('audit_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_milestones', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.transaction')),
            ],
            options={
                'ordering': ['sequence_order'],
                'indexes': [models.Index(fields=['transaction', 'sequence_order'], name='idx_mlstone_txn_order'), models.Index(fields=['transaction', 'status'], name='idx_mlstone_txn_status')],
                'unique_together': {('transaction', 'milestone_code')},
            },
        ),
        migrations.RunPython(
            code=backfill_payment_and_coordination_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]


