# Generated by Django 6.0.3 on 2026-09-01 14:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_transaction_references_and_payment_statuses(apps, schema_editor):
    Transaction = apps.get_model('core', 'Transaction')
    PaymentRecord = apps.get_model('core', 'PaymentRecord')
    import random

    for txn in Transaction.objects.filter(transaction_reference__isnull=True):
        year = txn.created_at.year if hasattr(txn, 'created_at') and txn.created_at else 2026
        for _ in range(50):
            cand = f"DL-TXN-{year}-{random.randint(100000, 999999)}"
            if not Transaction.objects.filter(transaction_reference=cand).exists():
                txn.transaction_reference = cand
                txn.save(update_fields=['transaction_reference'])
                break

    for pmt in PaymentRecord.objects.all():
        if not pmt.status or pmt.status == 'CREATED':
            if pmt.payment_status:
                pmt.status = pmt.payment_status
                pmt.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_escrow_add_payment_records_and_trust_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('status', models.CharField(choices=[('REFUND_REQUESTED', 'Refund Requested'), ('REFUND_REVIEW', 'Under Review'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_INITIATED', 'Refund Initiated with Provider'), ('REFUND_CONFIRMED', 'Refund Confirmed by Provider'), ('REFUND_REJECTED', 'Refund Rejected')], db_index=True, default='REFUND_REQUESTED', max_length=40)),
                ('reason', models.TextField(help_text='Reason for the refund request')),
                ('provider_reversal_reference', models.CharField(blank=True, help_text='M-Pesa reversal receipt or bank reversal reference', max_length=100, null=True)),
                ('evidence_metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='idx_pmt_txn_status',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='idx_pmt_payer_status',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_txn_tenant_crt_at',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='account_reference',
            field=models.CharField(blank=True, help_text='Account reference sent to provider', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='checkout_request_reference',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa Daraja CheckoutRequestID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='merchant_request_reference',
            field=models.CharField(blank=True, help_text='M-Pesa Daraja MerchantRequestID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='purpose',
            field=models.CharField(choices=[('LAND_PURCHASE', 'Land Purchase Consideration'), ('DIGILAND_SERVICE_FEE', 'DigiLand Platform / Coordination Fee'), ('SURVEY_FEE', 'Surveyor Verification Fee'), ('LEGAL_FEE', 'Legal Conveyance Fee'), ('INSPECTION_FEE', 'Physical Site Inspection Fee'), ('OTHER', 'Other Service Fee')], db_index=True, default='LAND_PURCHASE', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('CUSTOMER_ACTION_REQUIRED', 'Customer Action Required (STK Prompted)'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_CONFIRMED', 'Payment Confirmed by Provider'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('PAYMENT_EXPIRED', 'Payment Expired / Timed Out'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('PAYMENT_DISPUTED', 'Payment Disputed'), ('INITIATED', 'Payment Initiated (Legacy)'), ('PENDING_CONFIRMATION', 'Pending Provider Confirmation (Legacy)'), ('CONFIRMED', 'Payment Confirmed by Provider (Legacy)'), ('FAILED', 'Payment Failed (Legacy)'), ('REVERSED', 'Payment Reversal Recorded (Legacy)'), ('CANCELLED', 'Payment Cancelled (Legacy)')], db_index=True, default='CREATED', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Primary DigiLand transaction reference (e.g. DL-TXN-2026-000182)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('CUSTOMER_ACTION_REQUIRED', 'Customer Action Required (STK Prompted)'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_CONFIRMED', 'Payment Confirmed by Provider'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('PAYMENT_EXPIRED', 'Payment Expired / Timed Out'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('PAYMENT_DISPUTED', 'Payment Disputed'), ('INITIATED', 'Payment Initiated (Legacy)'), ('PENDING_CONFIRMATION', 'Pending Provider Confirmation (Legacy)'), ('CONFIRMED', 'Payment Confirmed by Provider (Legacy)'), ('FAILED', 'Payment Failed (Legacy)'), ('REVERSED', 'Payment Reversal Recorded (Legacy)'), ('CANCELLED', 'Payment Cancelled (Legacy)')], db_index=True, default='INITIATED', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='provider_reference',
            field=models.CharField(blank=True, db_index=True, help_text='M-Pesa receipt, bank reference, or provider confirmation ID', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['checkout_request_reference'], name='idx_pmt_chk_ref'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['transaction', 'status'], name='idx_pmt_txn_status_v2'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['payer', 'status'], name='idx_pmt_pyr_status_v2'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['purpose', 'status'], name='idx_pmt_purp_status'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_reference'], name='idx_txn_reference'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.paymentrecord'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_records', to='core.transaction'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['refund_reference'], name='idx_rfd_reference'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['payment', 'status'], name='idx_rfd_pmt_status'),
        ),
        migrations.AddIndex(
            model_name='refundrecord',
            index=models.Index(fields=['transaction', 'status'], name='idx_rfd_txn_status'),
        ),
        migrations.RunPython(
            backfill_transaction_references_and_payment_statuses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
