# Generated by Django 6.0.3 on 2026-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_non_escrow_direct_settlement_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermfa',
            name='otp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='passkey_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='preferred_method',
            field=models.CharField(default='authenticator', max_length=20),
        ),
        migrations.AddField(
            model_name='usermfa',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='auth_method',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usersession',
            name='inactivity_timeout_seconds',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='usersession',
            name='mfa_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='accountdecision',
            name='decision_type',
            field=models.CharField(choices=[('PURCHASE_PROPOSAL', 'Purchase Proposal / Offer Authorization'), ('DUE_DILIGENCE_INITIATION', 'Initiate Due Diligence Request'), ('MEMBER_REMOVAL', 'Propose Member Removal'), ('CHANGE_MANAGER', 'Change Team Manager / Leadership Succession'), ('CLOSE_ACCOUNT', 'Close Account / Liquidation'), ('SALE_AUTHORIZATION', 'Authorize Property Listing / Sale'), ('EXPENSE_PAYMENT', 'Authorize Professional Service Payment'), ('CUSTOM_PROPOSAL', 'Custom Group Proposal')], db_index=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('DIRECT', 'Direct Message'), ('TRANSACTION', 'Transaction Thread'), ('TRANSACTION_PAYMENT', 'Payment & Transaction Thread'), ('ESCROW', 'Payment & Transaction Thread (Legacy)'), ('VERIFICATION', 'Verification Thread'), ('SUPPORT', 'Support Thread'), ('STAFF', 'Staff Internal'), ('GROUP', 'Group Conversation')], db_index=True, default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('CUSTOMER_ACTION_REQUIRED', 'Customer Action Required (STK Prompted)'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_CONFIRMED', 'Payment Confirmed by Provider'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('PAYMENT_EXPIRED', 'Payment Expired / Timed Out'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('PAYMENT_DISPUTED', 'Payment Disputed'), ('LEGACY_PAYMENT_RECORD', 'Preserved Legacy Payment Record'), ('INITIATED', 'Payment Initiated (Legacy)'), ('PENDING_CONFIRMATION', 'Pending Provider Confirmation (Legacy)'), ('CONFIRMED', 'Payment Confirmed by Provider (Legacy)'), ('FAILED', 'Payment Failed (Legacy)'), ('REVERSED', 'Payment Reversal Recorded (Legacy)'), ('CANCELLED', 'Payment Cancelled (Legacy)')], db_index=True, default='CREATED', max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='purpose',
            field=models.CharField(choices=[('LAND_PURCHASE', 'Land Purchase Consideration'), ('DIGILAND_SERVICE_FEE', 'DigiLand Platform / Coordination Fee'), ('SURVEY_FEE', 'Surveyor Verification Fee'), ('LEGAL_FEE', 'Legal Conveyance Fee'), ('INSPECTION_FEE', 'Physical Site Inspection Fee'), ('ADDITIONAL_DUE_DILIGENCE_FEE', 'Additional Due Diligence Fee'), ('OTHER', 'Other Service Fee')], db_index=True, default='LAND_PURCHASE', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('CUSTOMER_ACTION_REQUIRED', 'Customer Action Required (STK Prompted)'), ('PAYMENT_PROCESSING', 'Payment Processing'), ('PAYMENT_CONFIRMED', 'Payment Confirmed by Provider'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CANCELLED', 'Payment Cancelled'), ('PAYMENT_EXPIRED', 'Payment Expired / Timed Out'), ('PAYMENT_REVERSED', 'Payment Reversed'), ('PAYMENT_DISPUTED', 'Payment Disputed'), ('LEGACY_PAYMENT_RECORD', 'Preserved Legacy Payment Record'), ('INITIATED', 'Payment Initiated (Legacy)'), ('PENDING_CONFIRMATION', 'Pending Provider Confirmation (Legacy)'), ('CONFIRMED', 'Payment Confirmed by Provider (Legacy)'), ('FAILED', 'Payment Failed (Legacy)'), ('REVERSED', 'Payment Reversal Recorded (Legacy)'), ('CANCELLED', 'Payment Cancelled (Legacy)')], db_index=True, default='CREATED', max_length=40),
        ),
        migrations.AlterField(
            model_name='surveyassignment',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent Priority')], default='NORMAL', max_length=20),
        ),
    ]
