# Generated by Django 6.0.3 on 2026-09-01 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_usermfa_otp_enabled_usermfa_passkey_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Security Key / Passkey', max_length=200)),
                ('credential_id', models.CharField(db_index=True, max_length=512, unique=True)),
                ('public_key', models.TextField()),
                ('sign_count', models.IntegerField(default=0)),
                ('aaguid', models.CharField(blank=True, default='', max_length=64)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'credential_id'], name='idx_passkey_user_cred')],
            },
        ),
    ]
