# Generated by Django 6.0.3 on 2026-09-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_userpasskey'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversation',
            name='idx_conv_transaction',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='idx_conv_parcel',
        ),
        migrations.RemoveIndex(
            model_name='disputecase',
            name='idx_dsp_case_num',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='idx_msg_client_id',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_provider_msg_id',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_idemp_key',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='idx_pmt_dgl_ref',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='idx_pmt_prov_ref',
        ),
        migrations.RemoveIndex(
            model_name='paymentrecord',
            name='idx_pmt_chk_ref',
        ),
        migrations.RemoveIndex(
            model_name='refundrecord',
            name='idx_rfd_reference',
        ),
        migrations.RemoveIndex(
            model_name='rolepermission',
            name='idx_roleperm_role',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='idx_txn_reference',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='idx_session_user_active',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='idx_session_jti',
        ),
        migrations.RemoveIndex(
            model_name='verificationdocument',
            name='idx_vdoc_file_hash',
        ),
    ]
