# Generated by Django 6.0.3 on 2026-06-05 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='settings',
        ),
        migrations.AddField(
            model_name='organization',
            name='org_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Organization-level settings'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(blank=True, db_index=True, help_text='Custom domain for the organization', max_length=253, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='schema_name',
            field=models.CharField(db_index=True, help_text='PostgreSQL schema name for data isolation', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Is this the user's default/active organization?"),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_tier'], name='idx_org_sub_tier'),
        ),
    ]
