# Generated by Django 6.0.3 on 2026-09-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_remove_organization_settings_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='organization',
            name='idx_org_slug',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='idx_org_domain',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='idx_org_active',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='idx_org_schema',
        ),
    ]
