# Generated by Django 6.0.3 on 2026-03-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_landparcel_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded cryptographic signature graphic of the buyer', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contract_agreed',
            field=models.BooleanField(default=False, help_text='Has the contract been fully signed by both parties?'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded cryptographic signature graphic of the seller', null=True),
        ),
    ]
