# Generated by Django 6.0.3 on 2026-03-22 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agentkycapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='landparcel',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text='The verified agent assigned to review this parcel', limit_choices_to={'is_identity_verified': True, 'role': 'Agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parcels', to=settings.AUTH_USER_MODEL),
        ),
    ]
